### ISSUE TITLE
force refresh of thetvdb data and replace. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#103]
we need a way to replace old tvdb data like old thumbnails that get replaced on the site, the only way we can do it now is to find the folder where its hosted then refresh the info.
we should have a button that replaced all the data we have from each metaagent so nothing of the old will be left there (like old thumbs that have been replaced by many reasons) 

this should also be on a per series basis on the group page.

**Comment by da3dsoul** [comment]
@elementalcrisis I think this is find

**Comment by ElementalCrisis** [comment]
The episode thumbnails aren't replaced unless you delete the link and local files. Something we talked about for Client V2.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

This has since been fixed.
