### ISSUE TITLE
checks crc value with crc in filename under "Unrecognized tab"

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#109]
would be good if you had a better overview of the Unrecognized files in the "Unrecognized tab".
everything gets hashed for a crc value right? why not check that up against the crc code that is in the filenames and mark it for a easier overview of the tab as a hole, you can have a small icon next to the name of the file or color the name text with a color.

if it checks out with the crc in the name then it will have a green color and if it fails then it will be red. it can also not be colored at all if there is no crc code in the name (if its not found atleast)

my Unrecognized tab is always getting larger and larger it seems and something like this will give user a great overview over whats up with their files quicker. 

im thinking about something like how the Anime Checker does it: http://animechecker.blogspot.no/
(note on the picture, the user can pick their own color, better to use something neutral for JMM IMO.)
![](http://2.bp.blogspot.com/-d1gGA-jgrY4/UGOAErQ2SvI/AAAAAAAAACM/YU2jgeMVKPU/s1600/complete.png)

EDIT: this should also be present in the AV Dump page aswell.

**Comment by AreFinstad** [comment]
noticed you linked this issue on update 3.4.2.9 @ http://japanesemediamanager.github.io/changes.html
this is not the issue you should have linked too as this just talks about crc checkmarks on places they are not found ATM.

**Comment by jmediamanager** [comment]
Thanks, I will correct that soon

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
