### ISSUE TITLE
Download manager - save torrent files in folders

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#11]
**Reported by RickDB, May 8, 2012**

Currently using Vuze and would like the ability to download torrents to folders from JMM desktop and/or MA3 plugin.

The current version requires uTorrent but this option would make it compatible with a variation of torrent clients since most support importing from folders.

**May 8, 2012 werndlymob**

Ok will do, although it means the torrent monitor won't be useful.

However Vuze looks like it has the same sort of API that uTorrent does, so support could be added.

**Comment by ElementalCrisis** [comment]
Download features were removed from Shoko.
