### ISSUE TITLE
tagging subbing groups?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#111]
how about we can be able to tag subbing groups? that should also be viewable in the dupe and mulit tab in utilities. 

users can make tags themselfs as a note on how the group have performed before, if they have many errors or not and such.

also with the tags we can use its as a ranking system for the groups aswell (think we have an issue on this somewhere)

**Comment by jmediamanager** [comment]
Yup good idea

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
