### ISSUE TITLE
group filter folders/sorting/grouping

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#113]
i think we need a way to sort/manage group filters, maybe with folders like you did with the Predefined Filters that contain by Category and Year and then have filters under that folder.

we need a way to mange these for ourselfs and such i think so we can sort what we use the most and so on, this is esp more needed with the custom tags we already have  as more tags needs more filters. and it will also be even more needed once we get support for custom groups and opens up to everything people have (not just anime)

**Comment by jmediamanager** [comment]
Can you give some examples of what you mean?

**Comment by AreFinstad** [comment]
we already have an example in JMM Desktop already in the predefined filters,
where you press the group filter "predefined filters" and it will open another filter page that is removed from the full filter list, in there you also have two other filters that is by category and year.

i wish to be able to make such folders with the group filter system like we have in the predefined once. just to give the user more control and such.

i for one would like to use custom tags for content creators like Miyazaki Hayao or any other to have an own folder that all the creators are placed (ofc this is custom tags and all group filters should be able to be placed in whatever folder you create) 

just able us to create sub folders like this maybe.

[Filter Folder] -> [Custom Filter]
                      -> [Filter Folder] -> [Custom Filter]

just an example tho, an collection of filters grouped and ordered by the user.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
