### ISSUE TITLE
hideable side panels?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#121]
we should be able to hide the side scroller on the Collection Tab (where you scroll and select Anime) (togglable hide button at the top right maybe?)
you should also be able to go to the next series (and Previous, so we can go back and forth on one series at a time) on the right side of the same screen, this should also take consideration for what you have sorted for aswell.
this way you will have more screen space in general, esp if you like to browse on a 9:16 portrait setup or something of the like.

I think something like this would be great for smaller group filters and so on, also an random series button would also be good.

at this point I don't think the UI respects your screen space at all no matter how small you set the pictures (tho alot of users would set it to a large picture for the best quality viewing)

you should also be able to hide the tabs on the left of the "Utilities" tab for the same reasons aswell (mostly for Portrait mode screens)

you could embed the button line you use to resize the UI with, one click for hiding and showing it. two clicks to auto size for the text and info needed to display the list, and aswell just dragging it as always.

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

Various UI improvements have been made to our successor to the Shoko Client being developed which relate to this issue.
