### ISSUE TITLE
Subbing Groups should have the same position on each episode under the "Multiple Files" tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#123]
Subbing Groups should have the same position on each episode under the "Multiple Files" tab, it should sort the subbing groups alphabetically on per episode, this way it wont change place from time to time when you more from one file to another.

this is a small annoyance esp when working quickly, the subbing groups should not change place when doing this as it creates unnecessary confusions and user errors when there really shouldn't be. 

example: as its now you can have collected a series with two subbing groups, all episodes are covered but some specials are different. therefore you have to manage everything on a per episode basis since marking it all will delete files you want to keep aswell (specials)
when you go down each episode you will find at times that the subbing groups have their places swapped, say Doki subs on the top and Coalgirls bellow it, but all other episodes are the other way around.
just force the subbing groups to be sorted alphabetically per episode and this will fix it self, if you need to create a sorting function then it could also be good to be able to sort other ways aswell like screen res, File size, bitrate and so on.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
