### ISSUE TITLE
pinnable and custom tabs on main tab bar.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#125]
pinnable and custom tabs on main tab bar.
would be great to be able to pin group filters and series groups to the main tab bar on the top as there is alot of wasted space there already. 
(about 45% is being used ATM on a 1920x1080 res. alot more if its higher, there is even space for a few more buttons if you use portrait mode aswell (9:16))
you could pin your most used filters and so on without needing to go to the collection tab.
this could also be great for using Custom Tags to Pin series more permanently and so on.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
