### ISSUE TITLE
add more options for filter conditions

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#126]
add more options for filter conditions, not just In and Not In criteria.
the filters ATM is a bit limited on what you can do with them, you cant have something like a few categories and then add a custom tag on top of that without removing everything that does not for-fill both criteria.
we should be able to add conditions more freely.
example, having a main Anime Group filter that has the rules Not in with the categories 18+ and Sex. but some series might have that in them while not being Hentai for example Future Diary (there is a few more, aswell that I don't recall the names of)
since AniDB is so limited on what they allow on tags (they have deleted alot of mine since no one used them or they didn't value them) custom tags is a great thing, but sadly ATM the group filters does not work aswell as it could.

take a look at ComicRack and how they filter their content, they got a switch that makes the filter either match all the criteria or any of the criteria (say match everything for each criteria no matter if both criterias are in the same series group or not)

**Comment by da3dsoul** [comment]
I'll do this if I find time in the next week or so. (the include or exclude any or all)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
