### ISSUE TITLE
add subbing groups to group filters.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#127]
add subbing groups to group filters.
we should be able to use subbing groups for group filters, with the "In" "Not In" and "Any" criteria.
also all episodes aswell, that way we can more easily see who is missing something or has the wrong file (from the wrong subbing group)
would also be great if it checked AniDB if the subbing group has released the hole series aswell.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Groups are already an available filter item.
