### ISSUE TITLE
Server and Anime Notifications (new entries to group filters)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#128]
Server and Anime Notifications.

would be great if we could set our group filters to a watched state and JMM will inform us in a Notifications area that a new entry has been added too it.
great if you are using RSS feeds like i am and is always download new stuff (can be great if you set the custom tag, waiting for BD Completion with the filter All in BD, every entry there would have both the custom tag and have all episodes in BD)
something like this would be great for just following what the user wants to follow, whenever there is a new release added to whatever filter the user is set to it will notify the user in a list with quick links (or you can have it in the dashboard)

uses that can use this: have custom tags like Pinned (series you really care about) and every new entry would go in the notify area. collecting BD and waiting for BD completion like above. 
waiting for the series to finish (add the custom tag waiting for series completion and also have the complete series filter)

every time a change happens in these filters it would notify the user in its own place (greetings screen maybe? (do need to be placed somewhere so the user can find it later aswell!))

the option to set notification on a filter can be placed at the edit screen for filters.

the notification function could also be used for series groups & subbing groups aswell

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
