### ISSUE TITLE
The left pane in the collection tab should show episodes when double clicking on a series...

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#13]
**Reported by Craige1Emmott, May 22, 2012**

I know there is an episode tab in the main content section, but after using it for a while, the natural action feels like you should be able to double click through the collection to the file you want in the left pane. I keep finding myself automatically double clicking on the series to go to the episode list.

So double click on the left pane to go filter->group->series->episodes->play episode.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, this change will not happen.
