### ISSUE TITLE
Related And Similar tab lists a series that isnt on anidb 

### ISSUE THREAD

**Issue by Darken5** [ShokoAnime/ShokoDesktop#144]
When going through my anime checking out any related series, came to Kekkai Sensen. On the "Related And Similar" tab it says "Data Missing", clicked "Get missing data now" button several times before clicking the number linked. 10906. 
the full link is: http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10906

Which comes up as an error page on anidb: "Unknown anime id. This entry may have been deleted from the database."

need a way to refresh/remove invalid "related" anime's

**Comment by ElementalCrisis** [comment]
Seems like a bug that corrected itself.
