### ISSUE TITLE
Add Series to playlist (unwatched) adds missing files on the server to the playlist

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#157]
Add Series to playlist (unwatched) adds missing files on the server to the playlist, making the playlist long and uncontrollable (if it has alot of episodes like Naruto and One Piece).
Large series with +200 episodes should be able to use playlists aswell more smoothly when episodes is missing.

just double checked this myself. i got over 300 missing files on Naruto as a test, if i add unwatched (they are watched and JMM doesnt remember even.... also an issue) it will add all episodes of the series group no matter if i have the files or not. you cant really make playlists that way with larger series like that. 
it should only add files it has on server, but i think it also should add files that you dont have if you have unwatched files before it in the timeline (if you manage to miss a download or something (this is another way to inform the user that you have a missing file)) if this happens then JMM should tell you someway, with a popup or a blinking icon or something that you have a missing file in the timeline of the series (like if you have episode 1-2-3 and are missing 4 but have file 5-6 and so on. files that are missing in the middle of the series (unless its watch state is synced from somewhere)

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

Playlist support has been dropped as our new Shoko Client does not support playback at all.
