### ISSUE TITLE
Playlist tab should space out images and episode text to fit the screen

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#159]
Playlist tab should space out images and episode text to fit the screen, if two pictures are large and there is no space for the text then place it under the pictures, ofc this goes for the pictures aswell.
this is a huge problem for 9:16 monitors (people that have extra screens for surfing the web, chatting and Manga/Comics like to have it that way for its better for those uses)

see how the text is just a few words per line and there is two pictures in width aswell.
yes the left playlist panel is scale-able by the user, but the other things isnt. 
![](http://puu.sh/j1TZl/1b46c17f42.png)

**Comment by ElementalCrisis** [comment]
The image is broken, can you see if you can replicate and if so resubmit a new image?

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

Playlist support has been dropped as our new Shoko Client does not support playback at all.
