### ISSUE TITLE
Options on which episode is highlighted

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#16]
**Reported by werndlymob, Aug 1, 2012**

When you view the episode list and JMM Desktop and MA3, it automatically highlights the next unwatched episode.
Add an option so user can highlight
- Next unwatched episode
- Episode after the last episode watched (default)

This way episodes do not need to be marked as unwatched.

If the last episode watched is the last episode in the series go back to the first episode

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
