### ISSUE TITLE
re-hide-able info text (episode, series text and so on)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#160]
Episode text can be expanded to give the full text, but not closed again to the smaller state. we should be able to click it large and click it small, not just large IMO.
this goes for episodes previews/overviews at the Series Info Tab and not the Episode tab as that text is already set to show the full text. 
this issue is also an issue on the playlist tab when its showing the next episode. it can open and show the full text but not hide it again for the cut version. 
ofc this also goes for the pinned tab since its the same as the normal series info tab.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
