### ISSUE TITLE
rotating artwork (covers/fanart)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#161]
i know our media portal shuffles coved images from each time you see it, JMM downloads and hosts many many versions of covers for the same series if you let it. 
but JMM Desktop does not use it at all other than to be able to set whats used in MP.... shouldnt it also be used in JMM Desktop (aswell as the Plex app and other apps that may come)

**Comment by jmediamanager** [comment]
Could you split the 2nd issue out, as it is unrelated (have confirmed that it is a bug)

**Comment by AreFinstad** [comment]
done

https://github.com/japanesemediamanager/jmmclient/issues/171

**Comment by jmediamanager** [comment]
Thanks

**Comment by AreFinstad** [comment]
fanart also needs to work like this IMO

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
