### ISSUE TITLE
make playlists from Groups with more than one series in it?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#167]
could we have a way to let us easily make a playlist that covers all series groups within a group collection?
i guess the playlist can be set to follow a chronological order or a order by release dates to make it right. this might be great for series that have split up its seasons across more than one AniDB entry and so on. also good for movies and OVA's that is connected to it aswell. (like they release a movie at the time of episode whatever and then continue on with the series (or those OVA's that is episode ,5 and such))

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

Playlist support has been dropped as our new Shoko Client does not support playback at all.
