### ISSUE TITLE
watch priorities for unwatched files (like AniDB)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#168]
how about watch priorities for unwatched files?
the user can set their watch prio to what they feel like and JMM will push those ahead of others if the prio state is high enough.

we can add this to the sort button aswell, sort by prio and the highest prio states will be at the top.

this can be more refined than AniDB's aswell IMO, a 0-10 number rating maybe?

**Comment by jmediamanager** [comment]
Where would these priorities be used?

**Comment by AreFinstad** [comment]
mostly the dashboard i guess. was just a thought. AniDB got it in place, why not use it in some way. low prio on this to say the least.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
