### ISSUE TITLE
have series total size in series window

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#172]
the only place we have series size ATM is in the file summary (witch alot of the time if at at bottom as its the least useful among the tags and titles)

example picture for location and such.
![](http://puu.sh/j1Y3F/5eed19bd6d.png)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Shown in Web UI.
