### ISSUE TITLE
add multiple files to AVDump from Manual link screen

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#174]
we should be able to mark and add more than one file at a time in the manual link screen to add to AvDumb, ATM we have to open the episode info before we can add it to AvDump from that screen, 
would be better if we could highlight by dragging a box or click shift/ctrl and then have a button that will add highlighted to AvDump. you recently added this to the unrecognised screen and more options but we all seems to forget the manual linking screen.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Possible with upcoming Web UI.
