### ISSUE TITLE
custom filters in Metro Dash

### ISSUE THREAD

**Issue by Andy2244** [ShokoAnime/ShokoDesktop#175]
Hi,

i would like the ability to add my custom filters/default to the Metro Dash view.

**Comment by jmediamanager** [comment]
What do you mean by custom filters?
Do you mean you want to select a group filter you have created and have it appear in the Metro Dash?

**Comment by Andy2244** [comment]
Yes, that's the idea.

**Comment by jmediamanager** [comment]
Ok, it would probably work
