### ISSUE TITLE
Windows 10 Store Integration?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#183]
i just updated to Win10 from 8.1 and loving it so far and JMM works great so far.
but i noticed in the Win10 Store they support alot of Anime and such now. maybe JMM can use that somehow, like linking and opening shows in the app or something like that. maybe a way to add things you have brought on there to the JMM Library, just a thought. the Anime section is a bit lacking ATM, but it can get better.... maybe. atleast keep an eye out IMO.

**Comment by jmediamanager** [comment]
What do you mean when you say they support anime? Lots of apps?

**Comment by AreFinstad** [comment]
nhaaa they are streaming anime to you. 

![](http://i.imgur.com/9Q1CI3G.jpg)
![](http://i.imgur.com/Dukwcx9.jpg)

**Comment by ElementalCrisis** [comment]
This is something I don't see us implementing.
