### ISSUE TITLE
block tags from the Community Data Tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#189]
we need a way to block content in the Community Data Tab.
either with Tags (and Custom TAGs (this is important for me)) 
this way people with H Content wont have that content take up the list (like half of my list)
also people can use a custom tag to block normal series that is already checked and they dont want to see on the list again.

it would also be nice to be able to remove one group at a time (or multiple by highlighting) in your list. that way it will make the list alot shorter and manageable, easier on the eyes. when you know you have checked everything you need to do with linking of a series you can remove it from the list and move on to the next one, there is no need to it to stay there if you already done all the work on it.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
