### ISSUE TITLE
File renaming - truncate fields

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#19]
**Reported by werndlymob, Aug 9, 2012**

Ability to truncate a field to a certain length, e.g. episode names can get very long

**Comment by SL-Gundam** [comment]
Would really like this as I've already had 4 animes where i had to build in exceptions so that the rename would not fail

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
