### ISSUE TITLE
Series Info - Compact Concept

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#194]
![selected series overview - detailed](https://cloud.githubusercontent.com/assets/9443295/9357615/d01a21b2-463c-11e5-957a-c9e310b7343e.png)

As you can see in the above image, this is what a fully extend series info tab looks. All the information you need is there but personally I feel like it could be better displayed in a more compact setting. It might just be me but I like to utilize all my available space and made a concept of what a compact series info tab could look like.

![selected series overview - detailed - compact](https://cloud.githubusercontent.com/assets/9443295/9357614/d0183f8c-463c-11e5-81aa-c4cd5cc3bed8.png)

I combined the link tab with the menu tab as they pretty much served the same exact function. I was originally going to remove the edit, move and delete buttons and instead have an options button that when selected would show those three options but changed my mind.

In the series info part I added the additional titles, the next episode, tags and custom tags. For the additional titles I believe it should be based on the languages you have selected in settings so I removed the titles being displayed in languages I did not have selected. I took the next episode box from the metro view and added the file info and episode summary. There's a link the user can click to take them to the episodes page where they can read the full summary. I combined the tags and custom tag sections and in my example have the custom tags displayed first and in a different color. Users would be able to select how many custom tags they wanted displayed by default. For the additional ones they could click "click here to view all tags" and a small window, similar to the one when adding a custom tag would open showing the full list of tags. Adding custom tags is done the same way via the dropdown box, same with managing them. 

The series overview part like before just shows the overview. Sometimes the overview on anidb has weird breaks so when being shown it should be reformatted to remove these breaks. Something else I did not consider until now would be an option to change the source from AniDB to TvDB or MAL if the user wanted too. 

The links section is also the same, while it shows the empty ones in the image, ideally any empty ones should not be shown. There could be a settings wheel next to the word links that would allow users to link the series with the services not being used.  

I didn't change anything for file summary so nothing to really comment on. 

Again this is just my idea on how it could look, would love to hear what others think and maybe we can, as a community come up with a better display, if lwerndly allows it of course. :)

**Comment by jmediamanager** [comment]
Hi @ElementalCrisis thanks for taking the time to post your ideas. I'm pretty sure we have a similar issue, but we can discuss it here.

The first thing to remember is that for UI design we need to specify what the minimum screen resolution we are catering for.
In my case, I have gone with Width as the limiting factor at 1024 e.g. Monitors with a res of 1280x1024

So on a screen like that the series view looks like this (Need to take into account the collection side bar)

![snap2](https://cloud.githubusercontent.com/assets/6645153/9372186/e3fe0ab2-471e-11e5-8102-301b455afff7.jpg)

Having said that, taking into consideration some of your suggestions we could actually squeeze that next episode widget onto the side there.

Personally I feel that tags section doesn't warrant inclusion in the top section, just makes it look too cluttered. Although I do like the idea of custom tags being merged, so I might try to figure something out with that

I'll try a few things out when I have time, and post back some screenshots here over the next few days

**Comment by AreFinstad** [comment]
i would love for the UI to use more of the screen space alot us have. 
anyway we can make the UI scale-able by the window size? 
there is prob alot that needs to be changed for something like that to happen tho. 
JMMD already does auto fit text, so why not the hole UI element and let the user more freedom of placement aswell? 
should be criteria for something like this tho, so there isnt just one or two words per line and that sort of thing (in cases like that then the hole thing should be moved down where its more room) 

by having it auto scaling it would cater to every res and ever aspect ratio (i can use it better with a 9:16 screen (rotated)) and so on.

**Comment by jmediamanager** [comment]
Yeah i use floating elements where possible, but those sorts of things are quite difficult and require  a LOT of testing.

**Comment by AreFinstad** [comment]
thats too bad :C 
well if you ever do want to try it out, just release an open beta for it and send out a mass JMM message. im sure people would try and report on issues if they had any. i would think most of us would want the best Anime Manager we can get, testing and reporting on it helps that progress

**Comment by ElementalCrisis** [comment]
Thank you both for the feedback. I'd love to see UI changes and would be willing to help test as well if you need testers.  

For my example I just cut the series info tab out so the collection side-bar would still fit. Of course I used my resolution of 1920x1080 so I could see how there might be problems with smaller resolutions.

**Comment by AreFinstad** [comment]
hmm think hide-able side panels would also work great.
https://github.com/japanesemediamanager/jmmclient/issues/121

**Comment by da3dsoul** [comment]
![V2](https://shokoanime.com/files/clientv2/v4/Collection%20-%20Series%20-%20Series%20Info%20V0.90.png)

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, making these changes would be a waste of dev time. 

Various UI improvements have been made to our successor to the Shoko Client being developed which relate to this issue.
