### ISSUE TITLE
manual season approval for mods?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#197]
manual season approval for mods?
i noticed on series where there is more than one season on TVDB (like Pokemon where i got too (16 Seasons)) that sometimes there is no review link to approve for every season (i only had 1-5 that i could approve of (even a few of season 1 in different languages))
i think we should be able to input info manually aswell for approval for when there is none to approve. let us input the AniDB episode number and the season+episode number of tvdb.
that way we will be done with those series (till they get more seasons)  and they wont reappear at a later date for when we need to approve the other seasons that wasnt the first time.

[Only the first seasons is review-able yet there is many seasons left of the series]
![](http://i.imgur.com/lT8crOM.png)

EDIT: we should also be able to enter our own links from tvdb,Trakt and so on in case they are really wrong. i just had a trakt link that gave me an 500 Error on the trakt site.

EDIT 2: looks like when i search for the series and find the right and only one that i was reviewing it gave me the same error just by browsing trakt.

**Comment by jmediamanager** [comment]
Yeah, that would probably be a good option

The way to work around it at the moment, is to create the series in your own collection, and the add the links there

**Comment by AreFinstad** [comment]
now how do i do this. do i have to link a random file to the series in the unrecognized tab?
as i try to add a new series with the New Group button (as thats what the series is called in JMM) i can only choose a name and sort name, but i can NOT add a AniDB link, TVDB link or any of the sort as it has no files. 

in cases like this where i wish we had a Custom Groups option that is really fleshed out

**Comment by jmediamanager** [comment]
To do this.
Go to the "Utilities - Unrecognized" tab
You can then press the "New Series" button.

This allows you to create a series/group by searching AniDB (no episodes needed)

**Comment by AreFinstad** [comment]
ahhhh  thanks, i will do this alot then.

**Comment by AreFinstad** [comment]
the way we can do this is to have the normal Search window for TVDB/Trakt (like we do on the collection/pinned tab)


also a nice way to do this is to have a Open in Pinned Button (if you have it on the server) to let you use the episode viewer to link episodes https://github.com/japanesemediamanager/jmmclient/issues/218 (as that gives you are larger working picture and the UI is much better over how the search window is ATM)

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
