### ISSUE TITLE
Community Review Tab shows multiples of the same link

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#198]
Community Review Tab shows multiples of the same link.
alot of the time i find in the Community Review Tab that shows will and more than one line that says the same thing but from different users.

![](http://i.imgur.com/Aer8FBt.png)

this takes up space and clutters the screen, the username should be ignored (or grouped together) and if the same AniDB Episode and the Same Season+Episode is up for review then it should all be under one line.

small things like this will make the screen alot better to read with a glance (its not hard to read, but it could be faster and easier IMO)

**Comment by jmediamanager** [comment]
I will change it to allow grouping.
However having the user name is valuable as you tend to know who makes the correct linking.

**Comment by AreFinstad** [comment]
yeah, thats why they should all be grouped up in one column or something like that, atleast not have one line for each guy eventho its the same anidb episode linked with the same tvdb season/episode

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
