### ISSUE TITLE
File renaming - episode number options

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#20]
**Reported by werndlymob, Aug 9, 2012**

Episode number options
- Auto numbering (as it is now)
- Select left padding zero's
- any others?

**Comment by AreFinstad** [comment]
tvdb season supports with episode number. tvdb episode number aswell in case its different?


copy of a dupe issue i made a good while back:

[enhancement] support thetvdb Seasons in renaming rules.

there is no support for season renaming (you already support linking episodes to tvdb so they should know witch season they are contained with)

you should be able to let the renamer script rename after seasons and episodes like all other media servers. "[Animename] - SXXEXX - [Episode Title] [Version number][release group]CRC

by using such a naming method makes the other media servers aware of what kind of file it is (it will not know if its a series or a movie (MediaBrowser & Plex))

EDIT: if you want to read up on how Plex handles this then you can read here: https://support.plex.tv/hc/en-us/categories/200028098-Media-Preparation 
or here: https://oldwiki.plexapp.com/index.php?title=Media_Naming_and_Organization_Guide
they really cover all the bases here.

also a thing Plex does that you can do with the App, Theme Songs for series. Plex Support Theme Songs on Series if you browse a series .

**Comment by AreFinstad** [comment]
https://github.com/japanesemediamanager/jmmclient/issues/21 belongs here IMO. 
should be a part of tvdb season structure or another option entirely for episode types.

**Comment by ElementalCrisis** [comment]
Even though they are quite similar, I'm going to keep both open as they are different features.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
