### ISSUE TITLE
color code Episodes and Specials in the Community Review Tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#200]
would be nice if Episodes and Specials and others where color coded or split up in some way.
the way the UI and JMMD is ATM its hard to with just a glance if its an episode or special.

Here is one that nearly got away from me because i didnt see there was a difference between specials and episodes other than the small text.
![](http://i.imgur.com/BL8oJDo.jpg)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
