### ISSUE TITLE
can't open AniDB Titles in Community Review Tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#201]
i can't open AniDB Titles in Community Review Tab in the Comparison Window.
TVDB uses mostly english titles and at times there isnt an english title set to AniDB as official so its not used (maybe Romanization versions are used).
for further review depth its easy just to check the other titles that is saved on AniDB, but when i click the titles tab in JMM (inside the Comparison Window in the Community Review Tab) it does nothing, none of the buttons there work it seems.... this is something that would make the process faster, as of right now you have to open the link in your browser and check the titles there..... something we should not do as we already have a webpage open in JMM.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
