### ISSUE TITLE
Question: how do i review when there is no English Lnaguage Link?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#202]
i just had a a link up for review where the TVDB link was not in English at all but in Portuguese and the English link is different aswell.

Example:
AniDB link: http://anidb.net/perl-bin/animedb.pl?show=anime&aid=1105
TVDB link JMM wanted me to approve: http://thetvdb.com/?tab=series&id=80920
(note that all episode names is in Portuguese and not English) 

TVDB link i found by searching manually: http://thetvdb.com/?tab=series&id=157001
(the correct one and in English)

in such cases. do i approve the Portuguese link or do i ignore it and move on?
manual linking is again useful in such cases https://github.com/japanesemediamanager/jmmclient/issues/197

NOTE: at this time i moved on and didnt approve of it.... just in case.

**Comment by jmediamanager** [comment]
No don't approve it.
The link you see in that tab are all the links user have selected.
It doesn't mean they are "correct".

**Comment by AreFinstad** [comment]
yeah, i noticed that. its is correct... just not in the right language.
but ok, only English links only 
fair enough

feel free to close the issue then.... as i cant XD

**Comment by AreFinstad** [comment]
another thought while im here: 
i notice that the Review process only does one way, a base AniDB ID to a TVDB ID
is there anyway we could have both ways at the same time, where there is more than one AniDB ID spanning seasons and specials of tvdb/trakt.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
