### ISSUE TITLE
more than just AniDB ID Searching in Community Review Tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#203]
i notice that we can only search for direct ID tags, why cant we search for names of the series and so on? or do you want it to be as strict as it can be for it to be flawless?

**Comment by jmediamanager** [comment]
I'll put this in as an enhancement for now, although I did purposely restrict it for performance reasons

**Comment by AreFinstad** [comment]
ah, i see. well thats fair, maybe restrict it to ID's only? TVDB ID's Trakt ID's and so on? that way we can search both ways not just with AniDB.
also does not hit the system too much either..... i guess.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
