### ISSUE TITLE
alerting Community Moderators when Approval list become larger than [?]

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#204]
i think it would be great if the Community Moderators, this could be a setting the user could set themself at the Community Review Tab.
say alert if there is 50,100,200,500 series up for review in the Approval list.
this will push people and alert them to help out when there is new series out when they are released. this will obv get the list shorter alot faster which is better for everyone as its approved by someone.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
