### ISSUE TITLE
Feature Request: Add Torrent URL To Search Torrents

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#207]
Currently when you search for a series to download you're just shown all available torrents. The additional information you'd be able to read such as the uploaders information and comments is inaccessible forcing you to go to the site which defeats the purpose of the built in search. This additional information can make all the difference and save you both time and bandwith.

**Comment by AreFinstad** [comment]
thoughts on this, the Community Review Tab has a browser window that can view web pages, we should be able to click the torrent in question and let us open it in that browser..... or open in the normal browser we have (make it two buttons) 

tho in other thoughts, the sites just need a scripts for JMM to gather such things as Comments and Info and display it in a neat JMM way.

**Comment by ElementalCrisis** [comment]
Downloading is no longer supported.
