### ISSUE TITLE
auto compare Start Dates and/or episode Dates between AniDB and TVDB/Trakt

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#209]
would be nice if JMM could compare start dates or dates of each episode and give us a small green tick if it was matching, it will make the process almost flawless as how many series have the same start date and the same name. ofc this does not work if there isnt any dates on tvdb/trakt tho.
the Tick/cross (if it matches or not) should be located in another column for each link that is up for review.

all of this is obv located in the Community Review Tab.

**Comment by ElementalCrisis** [comment]
The one issues I've noticed is AniDB uses the original air date while most of the time TvDB uses the English air date. 

http://thetvdb.com/?tab=seasonall&id=72719&lid=7
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=253

**Comment by AreFinstad** [comment]
yeah, differnt dates and such is a pain and cant really be fixed. but when reviewing links for tvdb i do find that most of the time the episode dates aswell as first start dates is correct.... esp for movies and specials that is on tvdb. if JMM could just check the dates of the link that is up for review then it would be faster than to find the special site on tvdb and find the episode the user sent for review and then check either name/date of the release with whats on AniDB.

as i stated, this is for the Community Review Tab so its just for streamlining the Review process.

example, if AniDB ID has Startdate/episode date then JMM will check that up with either Startdate/episode date of the series on Review (where the users have selected a season and episode to which compare it too) ergo, the episode/special in tvdb with the same date of the one of AniDB would alot of the time be the correct choice (something that would be displayed in a simple fashion for the Reviewer of the link)

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use. 

Additionally, @da3dsoul TvDB system pretty much resolved this issue.
