### ISSUE TITLE
File renaming variable for episode type

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#21]
**Reported by Craige1Emmott, Aug 18, 2012**

There is no variable for the episode type. 

Trying to label specials as such in the filename but cant due to no variable for for episode type. There is a test for episode type tho.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
