### ISSUE TITLE
Related And Similar Anime Tab Suggestions

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#210]
![jmmd - related similar anime suggestions](https://cloud.githubusercontent.com/assets/9443295/9432327/36079f26-49d6-11e5-838f-4684b47b8aa9.png)

Using the screenshot above I already have 3/5 Similar Anime recommendations. Seeing how I already have them there's really no point in me re-downloading them so having the download button present is not needed. Perhaps there could be a setting to hide the download button for series you already have? 

![jmmd - similar anime suggestions](https://cloud.githubusercontent.com/assets/9443295/9432456/e31751a6-49d7-11e5-9e8c-f7cb76063047.png)

As you can see the series I had selected has quite a few similar anime recommendations. To make it easier to view I'd like to suggest that if you already have the series, then it should be reflected in that panel. In the image, I created two examples showing what it could look like, either the background is a different color or the background is simply white.

Also can we have it sort the related and similar anime alphabetically? It's not that important but would be a nice feature. 

Lastly, where is the data for the approval percentage being pulled from? For example Seiken no Blacksmith (http://anidb.net/perl-bin/animedb.pl?show=anime&aid=6546) has an approval rating of 16.7% yet on AniDB holds an average rating of 6.50 or if you're using the weighted ratings, 3.78.

**Comment by AreFinstad** [comment]
i do agree that we need more colors in out UI, we need color coding for everything almost IMO. if we have a series it should be green and so on...... ofc a theme would also go a long way (a theme system that could be user made to fit the criteria the user wanted) 

things that is already on your watchlist or must download list should also be colored in that way IMO.

**Comment by jmediamanager** [comment]
Thanks guys some good suggestions there.
I'll play around with a few things and see how it looks, my first thought is to just gray out stuff you already have.

The approval rating is provided by the API, and it is calculated when someone makes a recommendation, and other people up-vote those recommendations

**Comment by AreFinstad** [comment]
if you do decide on making a theme system and/or playing with colors, we do need a midnight/dark mode IMO :D hint hint

**Comment by ElementalCrisis** [comment]
From mockup.

![image](https://user-images.githubusercontent.com/9443295/183215988-eb0a6bfd-90cc-432d-9183-28e3c5ff5899.png)

You're welcome past me.
