### ISSUE TITLE
Share Custom Metadata and Thumbs with BTSync?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#216]
just had a thought, when the Custom Thumbs and/or Custom Metadata support gets added we should have a simple way to share all the thumbnail pictures and so on, something that is synced with everyone, maybe BTSync is the way to go instead of paying a host? just a thought tho :D

**Comment by ElementalCrisis** [comment]
This is outside the scope of Shoko and something better served as a plugin down the line.
