### ISSUE TITLE
manual linked episodes linked in Episode Tab is Ignored by Community Tab

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#218]
episodes and specials i manually change tvdb/trakt linking to in the episode tab of either the collection tab or the pinned tab gets ignored by the Community Review Tab, 

![](http://i.imgur.com/TL45ujN.png)
![](http://i.imgur.com/BPaZtlA.jpg)
![](http://i.imgur.com/tGGJnrW.png)

only way to make it show up there is to link them on the main page here like so:

![](http://i.imgur.com/0dW2cQl.png)
![](http://i.imgur.com/LLqWHaT.png)

also, we need a simple way to clone the episode and specials numbers from tvdb to trakt, as most of the time (never seen it otherwise) they are the same as Trakt syncs with TVDB for its info. (ofc this should also be able to go the other way aswell IMO)

EDIT: sorry for all the large pictures...... i just want to get my point over.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
