### ISSUE TITLE
Has TVDB but Not Trakt Links in Community Data Tab (Utilities)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#219]
we should have a way for the Data Tab to search our collection (or maybe even the hole Review Database (i would love this so everything got a review link for the tvdb side of things aswell)) 
to be able to show all series that already has a tvdb link but does NOT have a Trakt link at all (and/or does not have one reviewed)

this means we should be able to filter out everything else that isnt fitting the filter.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
