### ISSUE TITLE
auto approve from Mods?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#223]
Mods are in low number, to speed things out then all MANUAL links the mods make does get auto approved. sounds good?

this combining manual linking in episode list https://github.com/japanesemediamanager/jmmclient/issues/218 would speed things up alot. Mods have to be trusted and already just make its own link and approve that if they wished, would be faster to just auto approve the higher ranking mods. (once the settings screen is out then we can start ranking people by % and only people with a certain % will be able to auto approve or something like that)

**Comment by ElementalCrisis** [comment]
Agrred, anyone that's a mod should have any link they make automatically approved.

**Comment by jmediamanager** [comment]
Yup seems fine but I will think about it.

NOTE - If you do the links on the series screen, there is an option which says "Use My Links", which will approve all the links you have selected

**Comment by ElementalCrisis** [comment]
I've tried that and it usually tells me there's links pending and opens the community tab.

**Comment by AreFinstad** [comment]
yup, only works if there is NO links up for review.
i think that button should approve our links no matter if there is links up for review or not.

**Comment by AreFinstad** [comment]
i also think that even if there is links up for review it should be able to use the "use my links" button.
esp when you are the only one to actually link something up for review. 
(many times i can see im the only one that have sent a link to review and the "use my links" button would not work even tho im the only one on the review list.)

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
