### ISSUE TITLE
Approve by Highlighting Links in the Community Review Tab?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#227]
would be nice if we could highlight links and approve them on mass with Shift Marking, Control Marking aswell as Box Marking (not sure about this one tho), and then have a button on top to approve all highlighted links (from more than one user aswell for speeds sake)

alot of times i get screens like this:
![](http://i.imgur.com/VjVId6V.png)

you see there is ALOT of links here and all is going to be approved (since i made them).
Link by Highlight (this issue) aswell as Auto Approve Mod links https://github.com/japanesemediamanager/jmmclient/issues/223 would be great in cases like this.

**Comment by ElementalCrisis** [comment]
Agreed, the abilty to approve multiple links would be very welcomed.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
