### ISSUE TITLE
Add Default Label to uTorrent Downloads

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#23]
**Reported by maximo.piva, Aug 21, 2012**

This is a tricky one.

Since WebUI API is very tricky.

Approach 1:

1) GetListOfTorrents from uTorrent as OldGroup
2) Add The New Torrent
3) GetListOfTorrents again from uTorrent as NewGroup
4) Select All Torrents in the NewGroup not in the OldGroup that have the label Empty. You can exactly compare torrent with the Hash.
5) Set the New Label to that list of torrents

Problem with this approach, after adding a torrent, it's not immediate listed. Which mean, a subjective delay is needed between point 2 a 3. Also you could label false positives if the delay is too big.

Approach 2:

1) Add The New Torrent, and save torrent name in a ToDo List
2) On Every Torrent Refresh do a Levenshtein Distance of the torrent name in the ToDo List, on the list of torrents. If Match and Label is Empty, set the new label, and remove from the todo list.

This approach have the problem the name listed not necessary is the name of the Torrent.

Approach 3 (More Difficult)

Same as approach 2, but getting the name, parsing the torrent. Which will be exact. (I have a torrent deserialize code somewhere)

Here is the SetLabel Code.

private const string urlTorrentAddLabel = "http://{0}:{1}/gui/?token={2}&action=setprops&hash={3}&s=label&v={4}";

```
    public void SetTorrentLabel(string hash, string label)
    {
        if (!ValidCredentials())
        {
            logger.Warn("Credentials are not valid for uTorrent");
            return;
        }

        try
        {

            string url = string.Format(urlTorrentAddLabel, AppSettings.UTorrentAddress, AppSettings.UTorrentPort, token, hash, label);
            logger.Trace("Set Torrent Label : {0}", url);
            string output = GetWebResponse(url);

            return;
        }
        catch (Exception ex)
        {
            logger.Error("Error in SetTorrentLabel: {0}", ex.ToString());
            return;
        }
    }
```

**Sep 2, 2012  maximo.piva@nutzcode.com**

In fact torrent deserialize could be important, as you can list the content of the torrent to the user, before downloading it.

**Comment by anzerman** [comment]
:+1: this would be great :)

**Comment by ElementalCrisis** [comment]
We no longer support downloading.
