### ISSUE TITLE
Metro Dashboard - Characters Overview Issues

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#235]
So I noticed there seems to be a few problems with the character overview in the metro dashboard.

![jmmd - characters overview](https://cloud.githubusercontent.com/assets/9443295/9651305/b8ab78ea-51c3-11e5-8ae9-f8861ede75f8.png)

Issues:
- The characters with the extended boxes but blank bios actually have bios when you hover over them. 
- Characters with no images should not be shown. 

Suggestions:
- Instead of hover, why not click to view? This way you don't need to show the bio snippet, just the character image. 
- Maybe it's just me but some kind of indicator about potential spoilers. 
- Truncate names for initial display in character section. Full name when bio window pops up. 

![jmmd - character bio](https://cloud.githubusercontent.com/assets/9443295/9651304/b8aaf564-51c3-11e5-8925-8fcf375f854a.png)

Issues:
- Spoiler tags within the bios on AniDB are not respected and shows as [spoiler]text here[/spoiler].
- Long bios are cutoff with no link to read full bio. 
- links and formatting like the italics code not rendered properly.

**Comment by jmediamanager** [comment]
The bios are only shown for main characters.
The boxes are extended because the character names are too long, I will fix that by truncating them.

I think characters without images should still be shown as they are valid.

Personally I prefer the hover, and it was easier to code and see details more quickly if they exist.
I will look at fixing the spoilers and truncated bios

**Comment by ElementalCrisis** [comment]
Makes sense, the area would be way too big if each character's bio was shown. I thought it might because of the characters name length. For characters without images I suggest then having JMM show some character silhouette like TvDB does for actors just to avoid any confusion for other users. I do like the hover as well and can see why it's more beneficial. 

What about having all the characters on the same row and having it scroll through them? This would allow all the characters AniDB lists to show up instead of a select random group. Speaking of which, how does JMMD determine which characters to display? AniDB lists 37 characters for Zero no Tsukaima: Princess no Rondo and 27 of them are displayed in JMMD.

**Comment by ElementalCrisis** [comment]
Design modernized and improved in upcoming Web UI.
