### ISSUE TITLE
Feature Request: Different Image For Each Series In A Group

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#239]
![jmmd - multiple series same image](https://cloud.githubusercontent.com/assets/9443295/9786406/a5e54578-576e-11e5-99e2-ba53796f5aa0.png)

Because we can manually select the default image I'm putting this pretty low, almost at the bottom on the list of feature requests. It would just be a nice feature to have.

**Comment by jmediamanager** [comment]
I'm not actually sure what the request is?
Each series already has it's own image?

**Comment by ElementalCrisis** [comment]
Forgot the word unique, that's what I get for writing this right before I went to bed.

**Comment by jmediamanager** [comment]
Ah ok

**Comment by AreFinstad** [comment]
all of these have different images in AniDB, its pulling from TVDB or trakt in this case, JMM cant see the difference between pictures and only works out of ID's of the series and its images.
for something like this to work we need JMM to compare the actual look of the image (which i would love it would do) like say http://www.duplicate-finder.com/photo.html and easy duplicate finder and other programs like it. 

an image comparer would be nice as loads of images dupes happen once you add tvdb and trakt into the picture.

**Comment by ElementalCrisis** [comment]
Issue no longer relevant.
