### ISSUE TITLE
MP4 encoder with manual linking in JMM?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#248]
hey i just run into PlexTools a few days back and its pretty smooth IMO, it swiftly converts your files into mp4 files with codecs that will run on pretty much everything, meaning there would be no need to live transcode on the fly and such.

can find more about the tool here: https://github.com/jwdempsey/PlexTools.bundle

it is based on this tho: https://github.com/mdhiggins/sickbeard_mp4_automator
the original has more options and can be made to do pretty much anything you need by the looks of it.

tho im unsure if it will handle .ass subs and such as it just talks about srt subs.
for this to work we would need a way to log our manual links better aswell IMO (like having the original file as a link and info and having it in a simple folder/file we can backup) 

i think reencoding takes a long time most of the time, but plex tools is super fast for me atleast, makes it alot simpler to mass encode your hole library and never needing to worry about it is going to play on your phone/tablet/smartTV.

i also note no loss in quality either when you leave the video bitrate the same.

timed test:
Heroes Reborn S1E01, 
Runtime:43min 1.3GB file
Encoding Time: 11m15s
Total Times used (used to "Relocate MOOV atom" *_): 17m25s
*_ "Relocate MOOV atom to the very beginning. Can double the time it takes to convert a file but makes streaming faster" **

drawbacks from this tho is the it doesnt handle burnins when needed too (atleast i dont think so) so it rely's on the video player supporting the sub format.
huge plus side of this tool is that its so off-hands on everything, you just tells the PlexTool which file/season you want to convert and it does it for you and will rename the new file aswell as delete the old one aswell as re-add it to plex.

**Comment by ElementalCrisis** [comment]
This is outside the scope of Shoko and better served as a plugin in the future.
