### ISSUE TITLE
Manually linked files should be grouped by Series

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#25]
**Reported by hobbysavvy, Sep 18, 2012**

Lets say I have a 12 episode series and they were all manually linked to the same series. In the Manually linked tab it would be nice if it showed the series name and when it opened up it would show the 12 linked episodes. 

Right now it shows 12 different entries and this gets really messy when multiple series needs to be manually linked.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

This is the default design in the Web UI for the Manually linked utility.
