### ISSUE TITLE
Enhancing Search Tab

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#258]
Right now the Search tab is pretty bland, it does exactly what it's supposed to but could use some display options as it only displays your search results in what I'm going to call large thumbnails. I'd like to suggest that list and small thumbnails be added to the display types. Also it should tell us the search results below the search bar, something like "X results found" would be nice if you're doing somewhat generic searches.

**Comment by AreFinstad** [comment]
on a note on the search tab, we should be able to search for info more clearly too IMO.
like for example a search like this: "tags: Mecha" "-tags: ecchi" for example that would search for one tag in this case mecha and then remove any series with the ecchi tag in it for example.

just an example tho, this should work with almost everything JMM handles tho IMO, Tags, Creators, Characters, Languages and so on...

just my thoughts on the matter atleast.

a wordcloud could be nice too IMO, have a simple add/remove from search with the wordcloud containing all the data from the search already in progress.... kinda like how the booru sites handles tag searches with adding a tag and blocking it from the search you are doing.

**Comment by ElementalCrisis** [comment]
Agreed, that would make searching much better as well.

**Comment by jmediamanager** [comment]
To do what you guys are describing, would mean removing the functionality that searches while you type.
Instead I would move the searching from the Desktop to the server.
I will do this if no-one protests

**Comment by ElementalCrisis** [comment]
More functionality is always a plus! :)

**Comment by ElementalCrisis** [comment]
No longer relevant as Web UI search solves these issues.
