### ISSUE TITLE
folder manager, move and group folders after series. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#259]
i think we need a folder manager to group folders like the setting: 
"Automatically place related series into the same group".

this could tool should also handle tvdb season folders aswell IMO: https://github.com/japanesemediamanager/jmmclient/issues/86

it should also work in series splitting across more than one folder and should try to group up the series in one folder/subfolder for the IP. (meaning if more than one season/group from a series is spread out over more than one drive it should try to move them to the same drive. https://github.com/japanesemediamanager/jmmclient/issues/67 )

what i also would like to see is harddisk space managment in a way, atleast to be able to see how much space is left on the drive when using the tool.

if there is no space on the drive but a series/group is split up across more than one drive it should try to swap places with another series that is nor part of a series/group with more than one season.

this should be a new Utilities tool and should be hosted there.

on note, this tool should also be able to set a new standard folder for a series/group as JMM cannot do this as of yet. only way to change where new series files gets moved to is to delete the group in JMM and then move the files to the new folder for then to import it.

all in all, folders should try to be in folders and subfolders after the series and group.
like this: 
-Naruto- mainfolder
            -Naruto- subfolder
            -Naruto Shippuden- subfolder

or the season way:
-Naruto- mainfolder
            -Season 1- subfolder
            -Season 2- subfolder
            -Season 3- subfolder
            -Season 4- subfolder
            -Season 5- subfolder
and so on......

season folders should ofc work with the season renaming and use tvdb seasons and episodes when using this folder mode like this issue: https://github.com/japanesemediamanager/jmmclient/issues/85

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/504

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

Referenced in main issue on server.
