### ISSUE TITLE
Better tools for dealing with location of previously hashed files.

### ISSUE THREAD

**Issue by bmfrosty** [ShokoAnime/ShokoDesktop#260]
My directory organization is a mess.  I've got files everywhere.  JMM already has functionality for moving files around with "Drop Source" and "Drop Destination".  It just needs a little bit more front end love.

Specifically what I'm looking for is a function in the GUI where I can select a series, have JMM evaluate each file in the series for location and make a determination if it's in the correct "Drop Destination" directory.  If it's in the correct directory it leaves it alone, if it's not, it moves it to the correct directory in "Drop Destination".  After this it updates the database with the new location of the file.

Secondarily this feature should have a checkbox for also renaming the file in the process.

Tertiarily there should be a checkbox for rehashing files after they're moved and renamed and comparing the hash to what's already in the database.  This really only needs to be used when moving files between filesystems.

**Comment by jmediamanager** [comment]
I think I have an issues somewhere in the system to show a summary of which folders your files are in.
The aim there was that you could select which folder you want to move any new files to.

But I also have make sure this is compatible with other requirements regarding users who want to have a root main folder. i.e. they want to move and rename files using TvDB season structures.

There is no need to re-hash the file, as the hashes stay the same regardless of the file name or location.

My inclination is that you have the ability to select a "drop destination" per series.
If you using default type settings, all new files will go here.
If you have chosen to use TvDB style renaming, it will create sub folders under this destination e.g. "Season 1", and moves the files there.

**Comment by bmfrosty** [comment]
I've been digging into the GUI more, truthfully, if it could just be added to the rename utility, it would probably make the most sense.  A checkbox, and a scheme pulldown.

I won't pretend that it's a trivial change, but it's one that I'd love to see.

**Comment by anzerman** [comment]
I think this would be good. If there was a way to have JMM organise existing files into correct series folder names etc that would be great. Especially useful for people who and new to the software and want to reorganise everything

**Comment by jmediamanager** [comment]
Will be partially covered here
https://github.com/japanesemediamanager/jmmserver/issues/142

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/504

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

Referenced in main issue on server.
