### ISSUE TITLE
output starting year into series folder name

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#266]
hmmm would be nice to have an option for outputting the starting year for series folders
like so: [series name](year)

the same folder structure other media servers use.
makes things much easier to use with other media servers.

ofc this is more for other media server support like the season renaming and season folders we already have issues for.

**Comment by da3dsoul** [comment]
Making this part of #504

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

Referenced in main issue on server.
