### ISSUE TITLE
autoupdate notification

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#271]
If we are left without autoupdate, why not make autoupdate notification?
Client download/parse xml/txt from network location with number of current version, if the downloaded version is higher than current installed one message box about it with download.html + the star icon that was there before.

This could be checked each 1h-1d ?

**Comment by ElementalCrisis** [comment]
Autoupdate was taken out due to its unreliability. I Believe @jmediamanager had a replacement in mind but did not have the time to implement it for the next version so now it's just the update prompt.

**Comment by jmediamanager** [comment]
At the moment it does what you describe, but only when you start Server/Desktop.
If there is a new version available it will prompt you to download

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change.
