### ISSUE TITLE
Community links does not get uploaded when JMM autolinks trakt links from tvdb choice. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#278]
seems like when you have a show without tvdb and trakt links and if you link the tvdb link correctly it will auto link the trakt link correctly (not sure if these are tied together but).
when this trakt link does get linked in JMMD it does NOT upload that info to the Community JMM Servers so we cannot review these links.

i just tested this now and it happens every time i let JMMD link trakt links automatically after a tvdb link. 

editing the trakt link and confirming it does ofc upload it again.

with this bug active we would be really limited on what gets uploaded to the review server.

**Comment by ElementalCrisis** [comment]
The Community Tab is no longer in use.
