### ISSUE TITLE
Select default image for a group separate from a series (could be an override)

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#28]
**Reported by windfury000@yahoo.com, Oct 14, 2012**

Sometimes, you have a poster for the whole series (group) itself that you want to separate from the season (series) posters.

Like an image for the group that says complete collection, the rest can then make use of posters which has titles that have: season 1, season 2, and so on.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Possible in the upcoming Web UI overhaul.
