### ISSUE TITLE
[Request] Bring Back "File Summary" in Main Info Serie Tab

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoDesktop#281]
Hi!
I don't like the new "Files" tab in "Series info"
I prefere like it were: in the main tab and "File Summary"
Or can you add a option to choose?
Thanks! :)

**Comment by AreFinstad** [comment]
aslong as its an option its fine with me. i love the new tab as its actually not totally useless like the old one was IMO.

**Comment by misakitchi** [comment]
I really prefere the "Info Files" in Main tab (in "Full Series View")
So can you please add an option to choose?
Thanks! :)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Viewable in the Web UI.
