### ISSUE TITLE
Changes done to the renaming rules on multiple Clients are not loaded until client restart

### ISSUE THREAD

**Issue by miracle152004** [ShokoAnime/ShokoDesktop#305]
If you have the JMMClient running on multiple systems (i.e. PC and Laptop) and change the renaming rules. These Changes are not loaded into the other client until you restart the client.

Maybe the values could be loaded from the server again if you switch the Script or if you change the tab.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
