### ISSUE TITLE
Sort Names being honored intermittently.

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#306]
Some **Groups Sort** Names are not used properly for sorting when **Quick Sorting** or **Sorting** section in the **Group Filter** is set. Some examples:
- _A School Where Love Is Unnecessary_
- _The Testament of Sister New Devil_
- _The Dark Knight Ingrid_
- _The Irregular at Magic High School_
- _The Last Molester Train Next_
- _The Legend of the Legendary Heroes_
- _The Pet Girl of Sakurasou_
- _The Pollinic Girs Attack!_
- _The Princess Knight "Janne"_
- _The Seven Deadly Sins_
- _The Seven Impregnated Women Who Sneaked into the Night_
- _The Story of 15 Beautiful Girls Adrift_
- _The World God Only Knows_

With the beginning articles(A, The) removed in the **Sort Names** field for the list of groups above and selecting **Sort Name** and clicking **Quick Sort** they remain sorted to the **Name** field. ex. _The Seven Deadly Sins_ is sorted after _Tears to tiara_. It should sort after _Serial Experiments Lain_

Not all are this way. These Groups do sort correctly for me:
- _The Dark Knight Ingrid_
- _The Fruit of Grisaia_
- _The Melancholy of Haruhi Suzumiya_
- _The Qwaser of Stigmata_

Again with the beginning articles removed in the Sort Name field. _The Qwaser of Stigmata_ correctly sorts after _Queen's Blade_.

Note: @ElementalCrisis noted that _The Quaser of Stigmata_ did not sort correctly in his testing though it did in my collection.

Update: Sort name seems to work correctly in the **Select Series/Group** dialog in **File Renaming**. _The Seven Deadly Sins_ is being sorted by **Seven** and not **The**.

**Comment by ElementalCrisis** [comment]
This is a hard one to pinpoint, I'll leave it in the 3.7 milestone but I don't expect it to get fixed in time for 3.7 release.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
