### ISSUE TITLE
Some AniDB tags on some series are ignored.

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#307]
I set up a **Group Filter** with the **Filter Condition**: "Tag    Not In    18 restricted". Two anime with that tag are consistently included in it's listing:
- _Bakunyuu Maid Gari_
- _Innocent: Shoujo Memoria_

![screenshot - 2016-04-12 23_22_09-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/14484523/045079de-0106-11e6-8e03-73f84bbcb56c.png)

(I use a **Custom Tag** because of this. Helpfully, it illustrates the issue well in the screenshot.)

**Comment by ElementalCrisis** [comment]
I think this might be related to #243 which is fixed in 3.5. There is a beta for version 3.5 available which you can try, http://jmediamanager.org/beta/.

**Comment by naarcissus** [comment]
I'll check it out.

**Comment by jmediamanager** [comment]
@naarcissus Can you confirm that the tag appears here

![image](https://cloud.githubusercontent.com/assets/6645153/14660718/0465ddf2-06eb-11e6-980f-a627a9da70bd.png)

**Comment by naarcissus** [comment]
![screenshot - 2016-04-19 18_45_32-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/14661047/7522d98c-065f-11e6-87f5-977c41cebfb8.png)

**Comment by naarcissus** [comment]
Shit! Now I can't duplicate it. :expressionless:  All "18 Restricted" are properly being excluded/included in my DB. I don't know why. I've imported ~100 more episodes and restarted my system once... ... ... ...

**Comment by jmediamanager** [comment]
It is likelt to be some sort of caching issue, I will investigate

**Comment by ElementalCrisis** [comment]
Issue resolved itself.
