### ISSUE TITLE
Missing episodes/files not showing as missing

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#308]
I have many series which are missing episodes, but only one (_Blood Shadow_) shows up in the **Missing Episodes** group. 

![screenshot - 2016-04-13 01_50_33-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/14488361/c1f455bc-011c-11e6-9638-0a99dcf8a106.png)

Update: Just checked. The **air-date** for _Bust to Bust:..._ _Volume 3_ is 2014-03-17.

**Comment by ElementalCrisis** [comment]
I believe this has been mentioned before, I'm not sure on the exact reason, any ideas @jmediamanager?

**Comment by jmediamanager** [comment]
I can replicate this bug.
It seems to occur only when the episode missing is the last episode in the series.

The Episode count, as shown on the series info does not match the last episode number as shown in the episode list.

![image](https://cloud.githubusercontent.com/assets/6645153/14658930/fac85668-06da-11e6-9fbb-d85957bd2af7.png)
![image](https://cloud.githubusercontent.com/assets/6645153/14658941/10545806-06db-11e6-9570-9abfb70dd2d9.png)

**Comment by jmediamanager** [comment]
NOTE TO SELF - in the above case, it seems that the API originally provided an episode list with 26 episodes.
This was later updated to 25 episodes.
The code that updates AniDB series information, creates and updates episode info, but it probably doesn't remove episodes that are no longer valid

**Comment by ElementalCrisis** [comment]
Issue no longer relevant.
