### ISSUE TITLE
A way to start playing a series from the ep.1 on the **Info** page

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#310]
I would like a button on the **Series Info** page that would just open episode 1 in the default player. 

Better it would open them all in an auto generated default playlist. Possibly edited using check boxes in the **Episodes** tab. This would probably be better for those whose episodes may be in several folders and/or with players that won't just vacuum up all similar files in the same folder.

Even better, put a small button on the Group in the left column of the **Collection** page that would open the default playlist. For multi-series groups, another playlist that is a combination of the individual series default playlists. Thus, clicking the "**Play Now**" button on the group would load a playlist containing, say, seasons 1 and 2 of an anime.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
