### ISSUE TITLE
A way to choose a specific episode variation to play in a Playlist

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#311]
When in a **Playlist** that has episode with multiple files I'm unable to choose which file to play when I click **Play All**. I assume it's using the **Auto File Selection** settings, but I would like the ability to select specific file to play in a given playlist.

When I click play on a specific item in the playlist I'm given an option to choose. I think it would be better to have the choice when adding the episode so the list so that **Play All** will honor the choice.

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

Playlist support has been dropped as our new Shoko Client does not support playback at all.
