### ISSUE TITLE
Statistics Page

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#316]
I would really like to have something like a Statistics page/tab to show things like:
- Total number of series in the collection
- Total groups
- Total episodes
- Total time
- Total time of watched
- Total time of unwatched
- Most common tag
- Group with most series
- Group with most episodes
- Series with most episodes
- Series/Group with most Specials
- Series with most time
- Series with least time
- Total vote score of all series
- Average vote score (**My Votes** & Community votes)
- Et cetera ad infinitum

Maybe even stats pages for individual groups and series.

It's always interesting and sometimes compelling to find out how your collection adds up and/or how each stat compares with others in the community. Also, may be a decent way to define and test a standard set of methods to that can used for other features.

**Comment by ElementalCrisis** [comment]
I agree, put my vote behind this as well.

**Comment by ElementalCrisis** [comment]
Some of this data is present in the Web UI

![image](https://user-images.githubusercontent.com/9443295/106412894-986ba800-63fd-11eb-81e1-c94f1c3bc0ac.png)

The rest seems more user specific and most likely won't be added.
