### ISSUE TITLE
Image Scaling

### ISSUE THREAD

**Issue by RyssenRagnar** [ShokoAnime/ShokoDesktop#339]
Would it be possible to add images scaling after window width/height? To improve the experience for users [in the future] using higher resolutions. It would also be useful when scrolling through episodes since large episode images are no problem at fullscreen but are in windowed.

I would like it to have both the option to change the images by pixels (with no maximum value) or by scaling according to window size (with a percentage value that you can change). 

(I'm referring to the images for episodes, series, fanart and posters.)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
