### ISSUE TITLE
cast to smart devices. (like chromecast)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#346]
Windows 10 support casting built into the OS. 
there is some issues with the built in caster tho ( but another caster can always be used anyway.) 

the built in Win10 caster does not support flac (even when supported codecs are installed (tho i didnt test if windows media player played it correctly)) 
and it did not display softsubs.
it plays h.264 and acc audio just fine aswell i have tested it with dts and h.265 (not 100% flawless there just yet sadly) 

adding a caster of our own that is open source or something would prob fix these issues tho!

look at say popcorntime (soon to be called Butter) handles casting just fine to any device in general.

Casting enables any smart device to be the screen for your content really. dont need any other plugin or app to support JMM, as you are using the standard JMMD on Windows anyway to cast.

many people already have windows laptops, desktops and tablets. this will just make things easier to view anime on the big screen in general.

if a caster can be built into JMM and support things like flac and .ass subs and so on then it would be perfect. it would practically remove the need of any plugin you might have on plex and kodi. 

nothing would stop it from being able to cast from those plugins either. so you could in theory use the kodi plugin to cast to a tv for example.

**Comment by maxpiva** [comment]
You can actually cast from the plex plugin donno about kodi. I don't see how we can implement this without adding a transcoder.

**Comment by ElementalCrisis** [comment]
This is outside the scope of Shoko.
