### ISSUE TITLE
Search/Community Site updates

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#347]
Make the scripts for web connectivity(TVDB, MAL, etc.) and torrent searches into plugins, extensions, DB entries, etc.. The idea is to allow these to be updated without requiring a full update to JMM.

So when one of these sites changes something a fix can be pushed to the **Web Cache** server(or similar) to update(automagically or manually) "on the fly."

**Comment by ElementalCrisis** [comment]
With Shoko Desktop in maintenance mode, we will not be making this change. 

A more modular system is planned for long term but for Server, not Desktop.
