### ISSUE TITLE
Characters and Staff tab for Full Series

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoDesktop#353]
I was thinking it would be cool to have a group filter for staff eg all shows with Sawano Hiroyuki. Then, it occurred to me we don't even have the means to view it in JMM Desktop. You can view cast in the simplified view. Staff we don't even have a db for.

**Comment by misakitchi** [comment]
I was thinking the same!
Please add it! ^_^

PS: and i don't like "simplified view"...

**Comment by ElementalCrisis** [comment]
Definitely something that can be added. 

In regards to the simplified view, it's meant to be just a snapshot of the series with a small overview and episode info. We've talked about expanding the current two views and maybe adding another so if you have any ideas we'd love to hear them.

**Comment by misakitchi** [comment]
I have too much ideas but i m too lazy to add issues! :D

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Already done in upcoming Web UI.
