### ISSUE TITLE
Automatically add new shows from MAL

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [ShokoAnime/ShokoDesktop#364]
I have set JMM up to sync watched states to/from MyAnimeList.

When I add a new show to MAL I'd like it to be synced to JMM as well. This allows me to keep better track of things(as for example, the first episode would also show up as missing if no file is downloaded yet).

**Comment by ElementalCrisis** [comment]
After looking it over this will be a little more tricky than originally thought.

First, JMM uses AniDB as a base, which means we need an AniDB ID to create a new series, usually not a problem when hashing files as we can compare the hash and get the ID for the series it belongs to. For MAL what we'll need to do is use the approved community links as our reference point. User adds Naruto, it will compare the MAL ID with all MAL approved community links and when it finds it match, add the series. For series that don't have an approved community link there will be no easy way to automatically add the show. 

So instead what we do is have a utility that lists all MAL series that could not be able automatically approved and the user simply enters the AniDB, or like when manually adding a series can search by name and select the correct series. It creates the link and adds the show when in turns adds a new link for admin approval.

**Comment by ElementalCrisis** [comment]
Since we don't support MAL anymore, this issue is no longer relevant.
