### ISSUE TITLE
Show anidb.net's "hot anime" list on dashboard

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#37]
**Reported by Craige1Emmott, Jan 14, 2013**

Show the current trending anime on the dashboard by using anidb.net http api to pull the "hot anime" list.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

List functionality has been discussed for a post launch of the upcoming Web UI v4.
