### ISSUE TITLE
Allow deletion of multiple files simultaneously in JMM Desktop's Multiple Files utility

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#38]
**Reported by inferknox, Jan 14, 2013**

Could check boxes be added next to the files of each episode, so that files desired for deletion can all be selected, then a button pressed to delete all the selected files simultaneously?
As is, one has to delete one at a time, which can be tedious because JMM Desktop takes a while to become responsive after each deletion.

**Jan 15, 2013 imperialxt**

Isn't this already possible? you expand an episode under the list and it has multiple delete buttons there

**Jan 15, 2013 inferknox**

As far as I can see, there is only a delete button on each file, allowing deletion of one file at a time.
Note, the "Delete all" buttons by the release group boxes do not provide the function I'm requesting, as they delete a group of files by a specified release group, which isn't necessarily what one would want to delete when deleting multiple files.

**Comment by ElementalCrisis** [comment]
This is possible thanks to the changes @da3dsoul made.
