### ISSUE TITLE
Allow selecting and marking multiple files as watched in Episode List

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#39]
**Reported by inferknox, Jan 14, 2013**

Would it be possible to add the ability to select multiple files in the Episode List, and a button "Mark selected as Watched".
That way, one can select & mark multiple files as watched, even if they are not in sequence, eg, if only episodes 2,3 & 6 are watched, but 5 has been skipped; and it will also speed up one's ability to mark watched files, rather than doing it one by one.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Will be possible in the upcoming Web UI v4.
