### ISSUE TITLE
Show characters and actors in JMM Desktop

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#4]
Show characters and actors in JMM Desktop
As another tab on the Anime Info screen, and also in the dashboard view

**Comment by AreFinstad** [comment]
note, partly done. characters and actors are displayed (not flawlessly) in the metro dashboard series pages.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, this change will not happen. 

However, this feature is planned for the new Web UI.
