### ISSUE TITLE
AniDB and TvDB Linking Issue

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#400]
I've noticed a flaw in the way AniDB and TvDB series are linked. 

For example using the series 11 Eyes, the series lists multiple specials on AniDB where TvDB only lists one. A user who adds this show to their collection will automatically have the links added for them as they've been approved. This works as intended but has an unforeseen side-effect and that is how linking in general currently works. When you link a series it's not linking a specific episode but a starting point. Using our example the series has two approved links, one for the regular TV series and one for the special. 

However because our database is built using info from AniDB we have a big list of specials that TvDB does not and because we've linked the special, JMM automatically assigns each special an episode image and description using the approved TvDB link for the actual special. What this does is cause episode images and information from season 1 to be used for the remaining special as we only tell JMM where to start when linking.

I propose the following solutions 

Solution 1

What should happen is there should be a check that prevents the same episode/special/credit/trailer from automatically being assigned twice in the same series. There are cases where the same special is and can be linked twice if the series for example has multiple music videos listed on AniDB but a single entry on TvDB. Additionally, we want to keep this at the series level because there are episodes that are apart of multiple shows. 

Solution 2

An easier method would be to make it so any link that uses season 0 from TvDB does not follow normal linking behavior and simply stop auto-linking once it comes to the end of entries listed in season 0.

**Comment by AreFinstad** [comment]
solution 1 would not work with movies i would think as anidb has alot of entries that have movies in parts. 
that is the same movie and the same tvdb link (if it has any)

**Comment by ElementalCrisis** [comment]
@da3dsoul TvDB linking system resolved this issue.
