### ISSUE TITLE
Certain Filter Conditions Do Not Work

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#433]
Tested on 3.6

- [x] Anime Type - IN does not work and results with NOT IN vary.
- [x] Custom Tags - Both IN and NOT IN do not work.
- [x] Episode Added Date - None of the values populate the filter.
- [x] Group - Equals does not work, Not Equals populates with all groups except the selected one.
- [x] Has MAL Link - Includes all groups regardless, Excludes shows nothing regardless if MAL link is missing.
- [x] Has TvDB Link - Generated list does not account for changes made. 
- [x] Tag - NOT IN does not work
- [x] Year - Unable to select year.
- [x] Video Quality - Only works if one is selected

**Comment by misakitchi** [comment]
Its for the beta v3.6.0.1 right?
I have same issue... :(
Tag "18 restricted" is not working...

**Comment by da3dsoul** [comment]
Oh hey this exists

**Comment by da3dsoul** [comment]
Also, video quality

**Comment by da3dsoul** [comment]
@maxpiva just commit some fixes. Let's update or closed this

**Comment by ElementalCrisis** [comment]
Will do some testing and update with results.

**Comment by da3dsoul** [comment]
TVDb works

**Comment by da3dsoul** [comment]
Video quality kind of works, you can only select one with proper results. I'd like to be able to choose more than one and have it be treated as 'or'

**Comment by da3dsoul** [comment]
Removing Filter Conditions often does nothing. Editing tags, video quality, etc with lists of strings only takes two, and they are treated as 'and' rather than 'or'

**Comment by da3dsoul** [comment]
More strings can be added by hand with a keyboard rather than clicking in the list

**Comment by da3dsoul** [comment]
Okay, I think I've fixed several of these.

**Comment by da3dsoul** [comment]
Verified anything with csv style arguments now work.

**Comment by ElementalCrisis** [comment]
Any updates @da3dsoul?

**Comment by da3dsoul** [comment]
There are issues with almost all of the apply at series level versions of filters. If in apply at group mode, almost everything works now. Group equals doesn't work at all (you can't select groups properly). Anime Type works flawlessly. I think custom tags work now, but someone will need to double check. Haven't tested episode added. Has ... Link works. Tag filters work. Video quality works 100%. I think year is still broken, but the logic for that needs to be rewritten according to the functionality noted in drop scripts. (Summary: it'll be apply at series, and series will be included if they aired at any time in the year)

**Comment by da3dsoul** [comment]
Year is fixed now

**Comment by da3dsoul** [comment]
TvDB seems broken again.... Ugh

**Comment by da3dsoul** [comment]
Okay, TvDB works, and MovieDB works, the TvDB or MovieDB doesn't work

**Comment by da3dsoul** [comment]
Fixed TvDB, MovieDB, and Both

**Comment by da3dsoul** [comment]
@maxpiva the last of these (see op) are part of the desktop errors for filters

**Comment by da3dsoul** [comment]
Finally....fucking.....DONE!
