### ISSUE TITLE
Add a MAL Link to a show reset episode count in MAL

### ISSUE THREAD

**Issue by SubaruSumeragi** [ShokoAnime/ShokoDesktop#446]
When I add a MAL Link to a show in my 3.6.0.3 client, my progression and my score in MAL is reseted to 0. (Hopefully the status in MAL doesn't change.)

**Comment by hidden4003** [comment]
Did you have the score set in jmm at the time of adding or was it not set ?

**Comment by SubaruSumeragi** [comment]
The score was not set in jmm.

**Comment by ElementalCrisis** [comment]
The issue is with MAL and their API as you can't send watched state by itself, you have to send the entire series info which includes score. If you haven't rated the series in JMM then the score is 0 by default which gets sent to MAL.

**Comment by ElementalCrisis** [comment]
@hidden4003 and @RickDB, is this something we can prevent or fix?

**Comment by ElementalCrisis** [comment]
We currently do not support MAL.
