### ISSUE TITLE
Admin rights for user level shares

### ISSUE THREAD

**Issue by Stonedestroyer** [ShokoAnime/ShokoDesktop#452]
So a problem with windows is when you run windows application as administrator you need to have a registry key added for it to detect user level shares due to security reasons.

The issue happens when jmmdesktop is reading network shares on different host, the solution is
https://technet.microsoft.com/en-us/library/ee844140(v=ws.10).aspx
EnableLinkedConnections is the registry key that causes all this, apparently enabling it causes some security issues not documented.

I guess having the registry key set as 1 on jmmdesktop install and saving a value of the default key when uninstalling to revert, or perhaps recode jmmclient without requiring admin rights.

**Comment by SL-Gundam** [comment]
Wouldn't it be easier to just use UNC shares instead of mapped network shares? Works perfect for me

BTW if this is added to the install of JMM desktop please make it a setting that can be changed. I don't want or need this change on my system

**Comment by ElementalCrisis** [comment]
This is a user specific issue.
