### ISSUE TITLE
Freezes up when changing users hide tags

### ISSUE THREAD

**Issue by RickDB** [ShokoAnime/ShokoDesktop#462]
**Issue**

If you modify a users "hide tags" in Settings -> Users it will freeze (non-responsive) and has to be killed via Task manager afterwards.
Settings however do get applied so it does it store it correctly.

This is with latest JMMClient and JMMServer from todays master branch.

**To reproduce**

Add or remove an hide tag from a user and press save, it will hang shortly after pressing save.

**Comment by da3dsoul** [comment]
It's waiting for the server to say it's done updating the filters. It does come back eventually. It's already WIP for a fix

**Comment by ElementalCrisis** [comment]
@RickDB can you check to see if this is still an issue?

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
