### ISSUE TITLE
Search view doesn't allow viewing series

### ISSUE THREAD

**Issue by RickDB** [ShokoAnime/ShokoDesktop#463]
**Issue**

When selecting Search view it allows searching and pinning of series however you can't open the series itself when clicking on it.

This is with latest JMMClient and JMMServer from todays master branch.

**To reproduce**

Select Search view from top menu and select a series, can click or double click on various areas however it will not open the series.

**Comment by ElementalCrisis** [comment]
I can't remember if it actually opens the series though I'm assuming it's supposed to so marking as a bug.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
