### ISSUE TITLE
cached metadata link display wrongly with some letters.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#465]
seems that the link pulled from the cache will not display correctly with series like say "Pokémon"
when the same linked is made locally and not automatically set it display correctly.

![](https://cdn.discordapp.com/attachments/96235819366371328/227462656683016193/unknown.png)

**Comment by maxpiva** [comment]
webcache probably has a encoding problem.

**Comment by ElementalCrisis** [comment]
@AreFinstad is this still an issue?

**Comment by ElementalCrisis** [comment]
No one else has reported this issue so either fixed or user specific.
