### ISSUE TITLE
Directory Support in File Rename Utility

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#47]
**Reported by IvanAhn, Mar 14, 2013**

I'd love to see directory support for file renaming!

Then I could do something like:

```
IF T(Movie) DO ADD 'I:\Anime Movies\'
```

or:

```
IF T(Movie) DO MOVEFILE 'I:\Anime Movies\'
```

I also like to keep my series and groups separate:

```
DriveLetter:\Anime\Series Name (x264.AAC.1080p-Doki)
DriveLetter:\Anime\Series Name (x264.AAC.720p-Underwater)
```

Makes it easier to burn to disc and delete, etc.  Currently, they just all go in the same directory if you use the Drop feature.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
