### ISSUE TITLE
Condensed Episode List for easier management.

### ISSUE THREAD

**Issue by naarcissus** [ShokoAnime/ShokoDesktop#473]
I would like to see an option similar to:
![image](https://cloud.githubusercontent.com/assets/3468111/18953751/c9028d98-8604-11e6-87bf-03f7528a7d91.png)

but for all episodes, regardless of seen status for easier management.

This is crazy:
![image](https://cloud.githubusercontent.com/assets/3468111/18953861/413b2d38-8605-11e6-9e13-7483febde8b9.png)

Maybe as a checkmark or dropdown selection on the episode list header:
![image](https://cloud.githubusercontent.com/assets/3468111/18954003/e57eeb96-8605-11e6-8832-0ba348a883be.png)

somewhat related i think: #339

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
