### ISSUE TITLE
Batch delete manual links

### ISSUE THREAD

**Issue by SeriousArthos** [ShokoAnime/ShokoDesktop#476]
Today I had to remove all my manual links in order to avdump and rescan them, but there's no option to remove all links or select multiple ones to delete. I think a batch delete would be a nice QoL feature, since removing one by one is very time consuming and there are no keyboard shortcuts (that I know of, at least) to facilitate this.

**Comment by da3dsoul** [comment]
@RickDB think you can get this one?

**Comment by RickDB** [comment]
Yeah will take a look :)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Will be possible in the upcoming Web UI version.
