### ISSUE TITLE
Multi Audio problems with File Rename Utility

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#48]
**Reported by IvanAhn, Mar 14, 2013**

```
// Audio Type
DO ADD '.%aud'
```

The above script results in FLACFLAC or AACFLACFLAC when it comes across a multi audio file. The notes above say:

%aud Audio codec (tracks separated with '

I don't see any separation and I only care about one track, so I just use:

```
DO REPLACE 'AACAAC' 'AAC'
DO REPLACE 'FLACFLAC' 'FLAC'
```

// etc...

The above code can become lengthy if groups release different tracks with different codecs, such as:
jpn audio: FLAC
eng audio: AAC
kor audio: AAC

Would be great to be able to specify track language and get codec for specified track:

```
IF D(japanese) DO ADD '.%aud'
```

So it should look for the jpn track and get that codec only.

**Aug 8, 2014  CatmanIX**

I'll add that this issue also results in tests for a particular audio format on files with multiple audio tracks. 

For instance:

```
IF J(FLAC) DO ADD 'FLAC '
```

Returns nothing on a file with multiple tracks, even if one or more of them is FLAC.

**Aug 8, 2014 CatmanIX**

btw, I think the description was trying to say the tracks would be separated with the ' character, which is how it displays in the file details (FLAC'AAC'AAC for example). 

I have a feeling that it's actually trying to return it as such but it's getting messed up due to the scripts use of ' and no apparent way to escape it for use as plain text, which may be the root cause of this issue.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
