### ISSUE TITLE
"music mode"? randomized OP & EDs 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#486]
"music mode"
random playlists or random opening of Opening and Ending videos to make a jukebox of sorts.
can be done with the internal mpv or a playlist for other players.
technically the mpv player could play these in a small format in the corner of the window aswell or even without the video part of it and just make it audio only. (would be really cool) if we ever get a new client ;) 

thoughts are it could be built into the client somehow (think about those blogs and such with music playbars on top/bottom)

JMM already handles the videos, it just need to play it a bit differently.
tho im sure it could be done with just playlists aswell.

blacklisting videos could be a nice choice, for those times its not just music and so on. 
could let people share that blacklist with the cache aswell.

im sure there is many that have many of those openings and so on. 

Moving on for a new function:
you could build on it even more once its in place.
you could let these audio tracks from the videos be played when you open the groups of the series, like plex does it for shows.
open the show and the music starts at a lower volume (use can set the volume in settings)
the video played as a part of the theme song can either be showing the video in the ui instead of fanart with the mpv player.
or play the audio without the video part.

**Comment by ElementalCrisis** [comment]
This is outside the scope of Shoko.
