### ISSUE TITLE
File Rename Utility: Compare strings such as series titles

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#49]
**Reported by IvanAhn, Mar 14, 2013**

```
// Movie: Don't use episode number
IF T(!Movie) DO ADD ' - %enr'

// Movie: English name in parenthesis
IF T(Movie);I(eng) DO ADD ' (%eng)'
```

The issue comes up when the Japanese name and English names are the same. Such as:

```
Summer Wars (Summer Wars) [91D39FC0] (x264.BD.FLAC-da.720p-Coalgirls).mkv
```

It's not a big deal, I just hoped I could do something like:

```
IF T(Movie);IF (%ann != %eng) DO ADD ' (%eng)'
```

If  issue #339  is fixed, I may just use that instead.
https://code.google.com/p/jmm/issues/detail?id=339

Then I could choose whatever title I want to use.

**Mar 18, 2013 IvanAhn**

I just found this:

http://wiki.anidb.net/w/WebAOM#Move.2Frename_system

```
U | text | Unequal tags. U(eng:ann) checks that both %eng and %ann are defined and unequal.
L | text | Equal tags. L(eng:ann) checks that both %eng and %ann are defined and equal.
```

So I'm using this now:

```
IF U(eng:ann) DO ADD ' (%eng)'
```

**Mar 19, 2013  IvanAhn**

Maybe I was mistaken...

```
IF U(eng:ann) DO ADD ' (%eng)' isn't working anymore.
```

Maybe it was my imagination that it worked.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
