### ISSUE TITLE
manually set group folders. manually choose a new folder or choose a known folder.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#497]
manually set group folders. manually choose a new folder or choose a known folder.
be able to set a group "main" folder, either by clicking a single button and choosing a folder the server already knows. or by choosing a path manually with a folder tree. 

when choosing a main folder the desktop will ask if the user would want to move all the files of the group to the new main folder. this would cleanup paths that is wrong and make sure that the group is in one single folder.

this could prob be used with https://github.com/japanesemediamanager/ShokoServer/issues/504 somehow.

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

Referenced in main issue on server.
