### ISSUE TITLE
Allow user to select a default tab, and also default group filter when the client opens

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#5]
Allow user to select a default tab, and also default group filter when the client opens

**Comment by AreFinstad** [comment]
https://github.com/japanesemediamanager/jmmclient/issues/26 belongs here as 26 is a dupe IMO.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, this change will not happen.
