### ISSUE TITLE
Expanding Bookmarks

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#50]
**Reported by rickyvh001, May 2, 2013**

Hello, 

Currently the only way to use the Bookmarks section is via the related and similar anime feature. Can the ability to add bookmarks by the AniDB ID number be added in a future update? That way you can add anime without it having to be related or similar to something in your collection. Of course expanding further on this idea would be the inclusion of a notes box where you could put any additional information.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Bookmarks, as they currently are in Desktop will not be in the upcoming Web UI v4. We've discussed a modernized system and something to look into pos launch of the Web UI v4.
