### ISSUE TITLE
Episode title not updating despite having info in DB

### ISSUE THREAD

**Issue by Remnence** [ShokoAnime/ShokoDesktop#501]
![episode issue](https://cloud.githubusercontent.com/assets/1884580/21299417/13b2a5c6-c561-11e6-9d9b-ef866d73b37c.PNG)

**Comment by Remnence** [comment]
SQL Server 2014
Running locally as sa.

**Comment by ElementalCrisis** [comment]
Hello,

I don't have this issue, @Remnence can you try on the 3.8 beta and see if this issue is still present?

**Comment by Cazzar** [comment]
https://gfycat.com/FrailSecondaryCanine the issue seems to be resolved fine, just tested myself.
