### ISSUE TITLE
Missing Episodes - bufferSize error

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#523]
## Description

While cleaning collection duplicate/multiple file clean + remove missing I tab on `missing episodes` and hit 'refresh'
The following error came up:
```
The value of this argument must be non-negative.
Parameter name: bufferSize
Actual value was -2147483648.
```
Isin't this max int ?

**Comment by da3dsoul** [comment]
Yes, wtf

**Comment by bigretromike** [comment]
I don;t know but currently refresh is stuck as there is "Loading..." in there and nothing changes.
I'm just signaling that there is a problem there ;-)

**Comment by ElementalCrisis** [comment]
Tried to reproduce but I'm unable to, can you reproduce @bigretromike?

**Comment by bigretromike** [comment]
I had it once yestarday. but i'm using stable release. Also which commit was aiming to fix this?

**Comment by da3dsoul** [comment]
Nothing specific, but changes have been made in the area

**Comment by bigretromike** [comment]
oh, great than I should probably update in near future ;) to check if this problem is still there;
