### ISSUE TITLE
Related and Similar cover size uses Mini Calendar image sizes!

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#526]
Related and Similar cover size uses Mini Calendar image sizes.

as the title says really. this is a weird one, one might want to have those in different sizes after all. 

on the dashboard people might want it large to have large images and on the related tab they want it smaller so we can see all covers on the same screen without scrolling. 

Versions: (Daily at 17.03.2017)
Server: 3.7.0.1345
Desktop: 3.7.0.1134

this ofc might be an issue that comes from the new systems, in anycase a note.

**Comment by ElementalCrisis** [comment]
Removed Bug label and added Aesthetics.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
