### ISSUE TITLE
Delete button on collection did not delete the blank group

### ISSUE THREAD

**Issue by catchra** [ShokoAnime/ShokoDesktop#533]
@da3dsoul 
## LOG FILE
desktop
[2017-04-30.txt](https://github.com/japanesemediamanager/ShokoDesktop/files/966964/2017-04-30.txt)

server
[2017-04-30.txt](https://github.com/japanesemediamanager/ShokoDesktop/files/966978/2017-04-30.txt)

## Description
under the collection ->all menu on shoko desktop there is a blank group with 0 series in it
clicking the delete button did not do anything.

following a suggestion from CtrlAltDefeat on discord doing recreate groups under essential settings
fixed the problem
## STEPS TO REPRODUCE

i do not know how to reproduce this as i don't know how it happened

**Comment by da3dsoul** [comment]
This can also happen when a filter is applied at the series level, the group itself has series in it, but for some reason, a group isn't removed from the filter in some cases. It doesn't happen often, but I've seen it.

**Comment by da3dsoul** [comment]
Recreating groups will always fix this

**Comment by ElementalCrisis** [comment]
Tried and this doesn't seem to be an issue anymore. @catchra if you can reproduce on 3.8 then please reopen.
