### ISSUE TITLE
GUI Refactor for Manually Linked page

### ISSUE THREAD

**Issue by Jimmyson** [ShokoAnime/ShokoDesktop#534]
After importing files that were to be manually linked. I have frequently run into usability problems with the "Manually Linked" page. Often I am either choosing to dump all files listed, or a selection of files (similar to that posted in Issue #174).

To access each of the options, I must first reveal the Actions list under each file link, then make my option, and sometime navigate back to "Manually Linked" page (especially after selecting "Avdump2").

I propose utilizing a Table format and removing the reveal action, as since only the files are listed, and they are only ever in a one-to-one relation link, and also having a "Avdump Selected/All", "Delete Selected/All Link", etc. options at the head of the tab window.

![shokodesktop_2017-05-01_23-36-55](https://cloud.githubusercontent.com/assets/8276052/25580914/b9fc5ea2-2ec7-11e7-958d-b9a54218c4af.png)

**Comment by da3dsoul** [comment]
Yeah we know. It's old and needs completely resigned with batch in mind. Manually linked files in general need a lot of work as well. At least for UI, it will definitely be different in clientV2. Hop on our discord for more info on that​, clientV2 planning is public, and input, let alone help, never hurts.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Already done in upcoming Web UI.
