### ISSUE TITLE
Adding new series manualy

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#536]
## Description

I added few series manually and this error pop up few times. The row for series are getting creates as I can use those added series. Not always. Giving you guys info as this could be already fixed in dev version.

Database on MySQL, only used on latest stable version of server.

## STEPS TO REPRODUCE

Add new series, find it by name, add as new group and this pops up. Not always.
![sql_error](https://cloud.githubusercontent.com/assets/6052025/25949968/a907dc04-3659-11e7-9827-381caa4e7274.png)

**Comment by da3dsoul** [comment]
This isn't a quick and easy fix. I'm removing the milestone. If it gets narrowed down, then it can be fix.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

This error seems to have been resolved as no one else has encountered it since.
