### ISSUE TITLE
JMM Desktop - Problem with Continue Watching

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#54]
**Reported by throtran, Jun 4, 2013**

_What is the expected output? What do you see instead?_
Before the update:
"Continue Watching" showed all animes with unseen episodes and prioritized animes with at least one watched episode

After update:
I can only see two animes
none of them were recently watched

_Please provide any additional information below._
attached screenshoot, usually there is only one instance of JMM Desktop running

![untitled](https://cloud.githubusercontent.com/assets/6645153/3974616/61ad59ce-27f7-11e4-85e5-2b7c796a5363.jpg)

**Comment by Andy2244** [comment]
I have the same problem, the "Continue Watching" entry in the Metro list shows no entries at all, while the "Continue Watching (System)" under the Collections Tabs list 98 entries?

**Comment by jmediamanager** [comment]
Can you check one thing first.
Does it still happen after you restart JMM Desktop?

If it still happens can you send the error from the JMM Desktop log

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the bug reported in this issue will not be looked into.
