### ISSUE TITLE
Error with internal MPV could not load file assembly

### ISSUE THREAD

**Issue by catchra** [ShokoAnime/ShokoDesktop#545]
## VERSION INFORMATION

Server Version: 3.8.0.0 Beta

Desktop Version: 3.8.0.0 Beta

## LOG FILE
Desktop
[2017-07-26.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1177428/2017-07-26.txt)

Server
[2017-07-26.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1177441/2017-07-26.txt)
## DESCRIPTION

on desktop v3.8  when I try to play a vid with the internal mpv player I get this error

Could not load file assembly 'NutzCode.MPVPlayer.WPF.Wrapper, PublicKey=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

## STEPS TO REPRODUCE

click play on any video in dashboard's continue watching with the internal MPV player active in settings

P.S I don't think this will cause any problems but I put it here

MySQL DB Raspberry Pi 3 with Raspbian 192.168.0.4
Shoko Server Win7sp1x64 192.168.0.5
Shoko Desktop Win7sp1x64 192.168.0.2

**Comment by catchra** [comment]
The bug is still present in shoko desktop 3.7.0.1461 daily

this is the error:
Could not load file or assembly 'NutzCode.MPVPlayer.WPF.Wrapper, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

log:
[2017-08-28.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1255187/2017-08-28.txt)

**Comment by ElementalCrisis** [comment]
Can confirm, issue reopened.

**Comment by RickDB** [comment]
Looks like assembly version mismatch at first glance but will check it out.

**Comment by da3dsoul** [comment]
Thank God. Check Desktop\VideoPlayers\mpv\PlayerForm.cs

**Comment by RickDB** [comment]
All credits to RandRandom on Discord for finding the solution 👍 , applied and tested to confirm it solves it.
