### ISSUE TITLE
Files>Open not taking into account set local path?

### ISSUE THREAD

**Issue by nspiegl** [ShokoAnime/ShokoDesktop#549]
## VERSION INFORMATION

Server Version: 3.7.0.6

Desktop Version: 3.7.0.4

## LOG FILE

[Shoko Server](https://github.com/ShokoAnime/ShokoDesktop/files/1270388/Shoko.Server.zip)
[Shoko Desktop](https://github.com/ShokoAnime/ShokoDesktop/files/1270379/Shoko.Desktop.zip)

## DESCRIPTION

Did a quick search but could not find an already open/closed issue for this.

It appears that the "Local Path" directory is not being used with the open button under (Collection >> <Group/Anime> >> Files tab >> Folders) as when I click open nothing happens. Confirmed working under the "Episodes" tab.

I am assuming this is the issue as when I first started using Shoko I had not yet set a local path and experienced the same issue of nothing happening when using the other open buttons. Hope that makes sense.

This open does not work>>
![image](https://user-images.githubusercontent.com/25097788/29972701-95a36502-8f5f-11e7-9e49-55edd29c25e4.png)

This one does>>
![image](https://user-images.githubusercontent.com/25097788/29972747-bbd95664-8f5f-11e7-837d-aacb0585a17c.png)

Local Path set correctly as per below>>
![image](https://user-images.githubusercontent.com/25097788/29972771-dc2a2b5a-8f5f-11e7-8502-83f5293f9646.png)

## STEPS TO REPRODUCE
Read above

**Comment by da3dsoul** [comment]
This may be fixed for 3.8 already, but I'll check it

**Comment by da3dsoul** [comment]
@ElementalCrisis I don't have any mapped remote builds. Can you test the various places to open folders and tell me which, if any don't work?

**Comment by ElementalCrisis** [comment]
Works for me but Server and Desktop are on the same PC for me. 

@nspiegl can you try with latest daily and see if you can reproduce?

**Comment by nspiegl** [comment]
Already had a spare VM setup so decided to use it for this. Installed daily build with the following dates:

DESKTOP = 2017-09-02 16:02
SERVER = 2017-09-02 16:47

Can confirm it all appears to be working as expected now. Sorry all, should have done this before logging the issue. Still new to most of this only just having started using the program and github. Will make sure I do more thorough testing before logging an issue next time.

**Comment by da3dsoul** [comment]
No worries. In this case we had 8 months between releases and a lot of internal changes and fixes, so it's hard to tell if a problem still exists right now.
