### ISSUE TITLE
Metro Dashboard does not finish Loading

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoDesktop#552]
Server Version: 
docker cazzar/shokoserver:daily
Desktop Version: 
5c0fa8cafc4567ebd6d7a449285640765902eded

## LOG FILE

no errors in logs

## DESCRIPTION

After using Shoko Desktop for a while,
the loading animation for the Metro Dashboard never get to an end.
See gif below:

![shoko_desktop_not_loading](https://user-images.githubusercontent.com/6566469/30209061-5ddc1b3c-9496-11e7-86a1-98f61bd73fba.gif)

## STEPS TO REPRODUCE

Launch Shoko Desktop
connect to server of choice
select metro dashboard, click reload buttons, all good
work for a while, for example browse collection etc
go back to dashboard, click reload

**Comment by da3dsoul** [comment]
This is a duplicate, and the other has a sure way to reproduce

**Comment by da3dsoul** [comment]
It's listed in #548

**Comment by Baine** [comment]
difference is: i did not pin anything

**Comment by da3dsoul** [comment]
Hmm. Well I'll reopen this. If it's fixed after that one is, it was the same issue that could be triggered several ways

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
