### ISSUE TITLE
Metro series overview displays episodes not in my possession

### ISSUE THREAD

**Issue by LovShoko** [ShokoAnime/ShokoDesktop#553]
not sure if that is 3.8 bug or not anyway the metro series view displays episodes not in my possession
![Image](https://cdn.discordapp.com/attachments/96235819366371328/355876087328407572/image.png)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
