### ISSUE TITLE
Import folder mapping issue

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#554]
Server using local drives
Client on other machine
When trying to map Destiantion folder (which is local drive for server) as a UNC/SMB location in Client, It tells that "A drop folders cannot have different files systems" - @da3dsoul reffer this as cloud thing.

**Comment by bigretromike** [comment]
this is also in daily.

Workaround:
Uncheck 'Destination folder'
Add maping in client
Check 'destination folder' in server
refresh client

**Comment by da3dsoul** [comment]
I would like someone to fix this before 3.9, but I have too big of a list of issues that I'm taking care of myself. @Cazzar, @RickDB, @hidden4003, or @christian-roggia, would any of you please take a shot? It's probably just a stupid logic error.

**Comment by christian-roggia** [comment]
I will take a look at this issue, hope I can help.

**Comment by Baine** [comment]
fixed by c212fd0a8a2fffed78d98462a9fa98f4769646af and b481ab2a30ccd633637262feea866e382112a1be
