### ISSUE TITLE
SubGroups used in Auto Deletion dont work properly

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#555]
As example from Discord: 

>  think that "Auto Deletetion setting" dont work correctly or its not how I understand. I have almost identical 2 episodes. The only different is (resolution, codecv, codeca, group). Type order is: source, autostreamcount,subgrop, resolution. I added "Operation hnk" in subgroups as first. File with OP-HNK is 632x480,mp3,avi other is 640x358,aac. I would asume that if Types have SubGroup on 3rd place, and Operation HNK is on first on that list, that It would be picked. But it looks like it do weight-average ? and the fact that op-hnk is higher more points are added form lower resolution and audio codec ?

It looks like the groups are taken litteraly as string, because I cannot add or pick "OP-HNK" from list, and the next Type that it falls is audiocodec which ARR (the second group) wins. 

Adding textbox or checking twice what is checked for subgroup would be nice.

**Comment by da3dsoul** [comment]
Okay, I made it accept both short names and long names, but that will be in the list, it will simply be called by its long name: Operation HNK [anidb page](http://anidb.net/perl-bin/animedb.pl?show=group&gid=1593)
