### ISSUE TITLE
Clicking on "Duplicate Files" may cause ShokoDesktop to freeze

### ISSUE THREAD

**Issue by asmoranomar** [ShokoAnime/ShokoDesktop#556]
Server Version:  Shoko Server Mono Latest as of 9/17/2017

Desktop Version: Shoko Desktop 3.8.0.1021 and 3.8.0.0 (cloned for debugging on 9/17/2017)

## DESCRIPTION

Unknown what caused the issue, but some time after upgrading to 3.8.0.0 release, clicking on the Duplicate Files tab causes Shoko Desktop to freeze.  Initial troubleshooting consisted of letting the client try to work itself out of the issue.  Another recommendation was to run the "Remove Missing Files" on the process on the Server.

Per admin's recommendation, I ran a debug and received the following error message:
`System.Windows.Data Error: 40 : BindingExpression path error: 'ObjectType' property not found on 'object' ''VM_DuplicateFile' (HashCode=52008189)'. BindingExpression:Path=ObjectType; DataItem='VM_DuplicateFile' (HashCode=52008189); target element is 'ListBoxItem' (Name=''); target property is 'NoTarget' (type 'Object')`

## STEPS TO REPRODUCE

1. Launched Shoko Desktop
2. Clicked on Utilities
3. Clicked on Duplicate Files

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
