### ISSUE TITLE
Multiply Files - acting weird

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#557]
Sometimes I cannot delete files because clicking "Delete All" give me same results as attached picture.

Currently I have few rows here and clicking "Delete by preferences"  give me same results as attached picture.

Deleting file by hand lock the ability to delete file by clicking "DELETE" in episode row, but using "Delete by preferences" bypass that lock and remove the rows without any problem (lack of consistence)

![shit](https://user-images.githubusercontent.com/6052025/30524685-9869487e-9bf8-11e7-8214-11fb6d948eea.png)

Is there a way to synchronize what "DELETE ALL/DELTE BY PREFERENCES" see and what is shown in Multiply Files (because current both are different story)? 

Desktop version 3.8.0.1021

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
