### ISSUE TITLE
Bookmarks missing info

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#560]
When ever I hit "bookmark this anime to download later" from Dashboard (the anime have picture, name, description, anidb link) and i navigate to Bookmarks, the only things I see them are rows with:

> (X) anidb_id [edit notes]
> Not downloading
> Priority: 1

I tried download missing info from anidb, but that didnt resolve anything;

Is this a bug after removing bittorrent functionality or is intended ?

**Comment by ElementalCrisis** [comment]
Can reproduce, marking as a bug.
