### ISSUE TITLE
Missing Episodes - Out of Memory

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#562]
sd: 3.8.0.1021

When clicking 'refresh' I get popup with generic error message.
and this is throw to log.

> 
> [2017-09-22 12:15:01:276] Error|BackgroundWorker.OnDoWork => MissingEpisodesControl.workerFiles_DoWork => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__16(Object a, Object b, Object c, Object d)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at CallSite.Target(Closure , CallSite , Object , Int32 , Boolean , Boolean , Int32 )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at ActLike_IShokoServer_c5090e866d614be38bc22b0b4354ac23.GetMissingEpisodes(Int32 userID, Boolean onlyMyGroups, Boolean regularEpisodesOnly, Int32 airingState)
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_DoWork(Object sender, DoWorkEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 188
> ---> (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()<---
> 
> [2017-09-22 12:15:01:291] Error|ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.NullReferenceException: Object reference not set to an instance of an object.
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 174
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

ShokoDesktop on idle eats up 912mb of RAM. On pressing 'refresh' on missing episodes It goes over 2GB or RAM (with overall usage of 80%, System have 8GB) and then generic popup with log above.

Also when error ocurse SD holds onto extra 500mb (which in idle now takes 1,4GB of Ram)

Also refresh change to 'loading...' and after the error it dont go back, so each time I want to try it I need to shutdown SD to reset the button state

Edit: Currently My ShokoServer eats up 4GB (after refreshing each time)..... if someone asking (after some time it going down to 2GB - as server eats up almost 2GB while idle)

**Comment by bigretromike** [comment]
According to @hidden4003 its Memory Leak.
Also I dont see any warrning/error in server log

**Comment by bigretromike** [comment]
series : 2067
files: 15826

> @hidden4003 
> it might not be a leak and just too much data
> as it tries to process everything in one go no wonder it chokes(edited)
> so it has to be optimized somewhat I guess, maybe some limit
> from user perspective there is not much practical sense whether you get 100 missing or 1000 missing

**Comment by da3dsoul** [comment]
Try again on latest daily server. I probably fixed it.

**Comment by bigretromike** [comment]
Do I need to update both or just server?

**Comment by da3dsoul** [comment]
Just server

**Comment by bigretromike** [comment]
I tried. Server hit 3,6GB RAM, Client spike to 2GB RAM.
And I'm waiting 👍 
I will update info when there is any results (good or bad)
.. I'm testing it via network so it can take time its sending 17Mb/s for 10minuts now...
And "One or more errors occurred" on client

> 
> [2017-09-26 13:13:30:214] Info|App.Main => App..ctor App startup - Loading UI
> [2017-09-26 13:13:32:125] Error|VM_ShokoServer.get_Instance => VM_ShokoServer.Init => VM_ShokoServer.SetupClient Unable to connect to Shoko Server
> [2017-09-26 13:13:34:055] Error|VM_ShokoServer.get_Instance => VM_ShokoServer.Init => VM_ShokoServer.SetupClient Unable to connect to server.
> [2017-09-26 13:13:39:178] Info|ExecutionContext.RunInternal => Timer.MyTimerCallback => VM_ShokoServer.SaveServerSettings Error saving server settings:
>  System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia 127.0.0.1:8111
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__13(Object a)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at CallSite.Target(Closure , CallSite , Object , CL_ServerSettings )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at ActLike_IShokoServer_1eee077f0e684625afa3cd9bd2c40927.SaveServerSettings(CL_ServerSettings contractIn)
>    at Shoko.Desktop.ViewModel.VM_ShokoServer.SaveServerSettings() in C:\projects\jmmclient\Shoko.Desktop\ViewModel\VM_ShokoServer.cs:line 400
> ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia 127.0.0.1:8111
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()<---
> 
> [2017-09-26 13:20:15:262] Info|RoutedEventArgs.InvokeHandler => UnrecognisedVideos.lbSeries_SelectionChanged => VM_AnimeSeries_User.RefreshEpisodes Got episode data from service: The Rapeman Anime Version in 417.2865 ms
> [2017-09-26 13:20:15:849] Info|RoutedEventArgs.InvokeHandler => UnrecognisedVideos.lbSeries_SelectionChanged => VM_AnimeSeries_User.RefreshEpisodes Got episode contracts: The Rapeman Anime Version in 530.3853 ms
> [2017-09-26 13:20:15:849] Info|RoutedEventArgs.InvokeHandler => UnrecognisedVideos.lbSeries_SelectionChanged => VM_AnimeSeries_User.RefreshEpisodes Sorted episode contracts: The Rapeman Anime Version in 0.5006 ms
> [2017-09-26 13:29:30:512] Error|BackgroundWorker.OnDoWork => MissingEpisodesControl.workerFiles_DoWork => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__16(Object a, Object b, Object c, Object d)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at CallSite.Target(Closure , CallSite , Object , Int32 , Boolean , Boolean , Int32 )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at ActLike_IShokoServer_1eee077f0e684625afa3cd9bd2c40927.GetMissingEpisodes(Int32 userID, Boolean onlyMyGroups, Boolean regularEpisodesOnly, Int32 airingState)
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_DoWork(Object sender, DoWorkEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 188
> ---> (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()<---
> 
> [2017-09-26 13:29:30:560] Error|ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.NullReferenceException: Object reference not set to an instance of an object.
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 174
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bigretromike** [comment]
also the only different now is that server never free up RAM and sits on that 3,6GB RAM after Client throw error - which is even worst ;p

**Comment by bigretromike** [comment]
@da3dsoul any news ? need me to test something ?

**Comment by da3dsoul** [comment]
Not yet. I've been working on other things

**Comment by ElementalCrisis** [comment]
Issue most likely related to older version as this error hasn't been reported since.
