### ISSUE TITLE
Performace issues in 3.8

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#563]
I have noticed a serious performance reduction since last update (3.8.0.0).
The Client is very unresponsive and the main view (Dashboard) takes ~10 seconds to
load up.

Also, when viewing details on a series, it takes much longer now, to load and display the data.

**Comment by ElementalCrisis** [comment]
Any errors in your Server or Desktop log? How big is your collection and what is the DB type?

A ton of work went into making Desktop faster to the point where I can load OP in 3-5 seconds where before it took a minimum of 2 minutes.

**Comment by t0815** [comment]
I've got 2003 Series in DB. I am using mySQL Server Version 5,6 in performance Mode (Server Mode).
What i noticed : Only first view takes very long. If i refresh the main-view or open a previously displayed details-page again, it loads up faster (caching then i guess). If i restart the client, its slow again and fast after 2nd view again.

**Comment by da3dsoul** [comment]
Mhmm I wonder if Plex contracts are used in some places they shouldn't be. Plex contracts are the only thing with a generate and cache on demand model

**Comment by ElementalCrisis** [comment]
@t0815 provide more detail please. 

Whats the main-view? Are you referring to the dashboard and if so what version, regular or metro?

**Comment by t0815** [comment]
Yes, i'm referring to the dashboard - in old, non-Metro View.

**Comment by da3dsoul** [comment]
Those errors are unrelated, but should probably have an issue for themselves in Server. I don't use Trakt, so I've never noticed them.

Regardless, I've not experienced any significant lag (by comparison, Desktop is still a mess).

**Comment by ElementalCrisis** [comment]
Issues related to specific version of user as they haven't been reported since.
