### ISSUE TITLE
Hide Episode Image and Overview when unwatched not working anymore

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#564]
With 3.8.0.0, the settings under the "Display"-Tab for Hide Episode Image and Overview when unwatched
are no longer working.

Steps to reproduce:

1. Activate the options
2. open a series with unwatched episodes
3. Images and Overview is still visible

**Comment by ElementalCrisis** [comment]
Can reproduced, making as a bug.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
