### ISSUE TITLE
Episodes expanded detail view bug

### ISSUE THREAD

**Issue by xmodx10** [ShokoAnime/ShokoDesktop#565]
## VERSION INFORMATION

Server Version: Latest daily - 2017-09-27

Desktop Version: Latest daily - 2017-09-27

## LOG FILE

Server >> [Server.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1337467/Server.txt)

Client >> [Client.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1337468/Client.txt)

## DESCRIPTION

When expanding the details of multiple episodes at once and scrolling the view appears to bug out and mix up the file names/details, operations are also affected. Also episodes that weren't expanded become visible with the wrong info.

## STEPS TO REPRODUCE

1. Go to an anime and expand the details of 4 episodes>>

![image](https://user-images.githubusercontent.com/25097788/30916767-cbf305aa-a3cc-11e7-8029-e953790860a1.png)

![image](https://user-images.githubusercontent.com/25097788/30916820-e375d57c-a3cc-11e7-9886-e9124f424e63.png)

2. Scroll up and down the episode list.

A few of the episodes that were expanded are no longer in the same state and we have other episodes reflecting the wrong info>>

![image](https://user-images.githubusercontent.com/25097788/30916917-343d8126-a3cd-11e7-84e8-6be8d84deb94.png)

**Comment by da3dsoul** [comment]
All I have to say is WTF

**Comment by da3dsoul** [comment]
It's undoubtedly a virtualizing issue. I don't have a clue about how to fix it.

**Comment by bond4u** [comment]
I've seen it happen in "Multiple Files" view. After deleting couple of multiples, items magically expand themselves and show wrong info. Collapsing and expanding the item makes it show correct info.
![image](https://user-images.githubusercontent.com/66413/43153678-9e758ab8-8f7a-11e8-8f02-ef326487dd60.png)

**Comment by bond4u** [comment]
I guess it's "Recycled" VirtualizationMode issue. Elements are re-used which makes expanded state carry over from one element to another.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
