### ISSUE TITLE
Myanimelist assigment can not be removed or edited

### ISSUE THREAD

**Issue by Dexil123** [ShokoAnime/ShokoDesktop#566]
When you want to edit or remove a Myanimelist assignment in Shoko Destkop the program will do nothing.

**Comment by ElementalCrisis** [comment]
He's talking about the community link just in case there was any confusion.

**Comment by Dexil123** [comment]
I have also noticed problems when adding TVDB and Trakt links. 
- Sometimes TVDB doesn''t link doesn't link. Pressing update in the linking screen does nothing. 
- And sometimes I add a Trakt link, and after that a TVDB link. Adding the TVDB link removes the Trakt link.

**Comment by Cazzar** [comment]
5ee769535ae2fad0361d893c6a9c51bb51b536dc
