### ISSUE TITLE
Search anime title containing special characters fail

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#57]
**Reported by marcojakko86, Jun 28, 2013**

I've seen a problem similar to this regarding file import that have special characters. The same issue appears when searching anime inside JMM Desktop that have special characters inside the name. I can post some examples:

「K」
 Chuunibyou demo Koi ga Shitai!
 Haiyore! Nyaruko-san

Strange enough, it CAN find some titles containing !, for example:

 Fullmetal Panic!

I'm using mysql, i've checked inside animegroup table and the anime are correctly listed, even in the JMM Desktop's dashboard appear correctly if i add a new episode.

**Jun 28, 2013 marcojakko86**

Overriding the name of the anime, changing to another, then reverting to the original one can solve the problem. Still, you have to do this for every anime you can't find correctly with search function

**Comment by ElementalCrisis** [comment]
I believe @da3dsoul fixed this a long time ago when he updated searching in general.
