### ISSUE TITLE
"A task was canceled." when accessing Utilities "Unrecognized" tab

### ISSUE THREAD

**Issue by kakure** [ShokoAnime/ShokoDesktop#570]
## VERSION INFORMATION

Server Version: Latest Nightly Build

Desktop Version: Latest Nightly Build

## LOG FILE

[Log Sample.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1502418/Log.Sample.txt)

## DESCRIPTION

When trying to navigate to the "Utilities" tab, which defaults to "Unrecognized" files, an error appears: "One or more errors occurred.".  This error comes up twice, then eventually the Utilities tab does display, but is empty (there should be unrecognized files to display).  It is possible to navigate to other options within Utilities (i.e. Duplicate Files, etc.), but it Shoko Desktop takes very long to load and is unresponsive.

## STEPS TO REPRODUCE

Images attached, showing steps:

![step 01](https://user-images.githubusercontent.com/27033914/33222306-3f99e486-d124-11e7-9679-d67547439cd2.png)

![step 02](https://user-images.githubusercontent.com/27033914/33222309-4229b884-d124-11e7-921c-23da676ec445.png)

![step 03](https://user-images.githubusercontent.com/27033914/33222311-44459980-d124-11e7-9a79-57834afe910d.png)

**Comment by da3dsoul** [comment]
Is there a relevant error in the server log?

**Comment by Cazzar** [comment]
It's possible as well that the function could be timing out.

**Comment by kakure** [comment]
Nothing within the server log, except normal hashing and aniDB fetching.

**Comment by kakure** [comment]
The error happens weather Shoko Desktop is run locally or remotely in perspective of the server.  Shoko Server is running on the same computer as its database (SQL Server 2016).  Shoko Server is running on one SSD, and SQL Server is running on another SSD.

**Comment by kakure** [comment]
The computer Shoko Server and its database are running on is a dedicated computer for Shoko Server and its database.  The computer is an i7 4GHz, with 16 GB RAM.  Programs, Databases, and target files are all on separate volumes.

**Comment by kakure** [comment]
Tried modification to IShokoServer interface:
[Rest("File/Unrecognised/{userID}", Verbs.Get)] --> [Rest("File/Unrecognised/{userID}", Verbs.Get, null, 300)]

With that timeout modification, it took 3 minutes 30 seconds and retrieved 95,655 unrecognized files.  The UI did load up, and displayed all unrecognized files.  I should note, that I had to pause all running tasks (hashing, importing, media info refreshing, etc.).

So, this is a bug, but it's an end-user induced bug, since I'm throwing an unreasonable amount of files at this thing.

**Comment by da3dsoul** [comment]
I can look at speeding it up, but that is unreasonable.

**Comment by ElementalCrisis** [comment]
What about loading it in chunks?

**Comment by da3dsoul** [comment]
I am not making a pagination list... I suppose what you mean is more a lazy loading virtualized list, but still. Sounds like a pain. I can see if I can find an easy implementation already written, but I'll not be writing my own when it's about to be replaced.

**Comment by da3dsoul** [comment]
https://stackoverflow.com/questions/7581732/wpf-datagrid-lazy-loading-inifinite-scroll

**Comment by da3dsoul** [comment]
I maybe able to do it without too much trouble

**Comment by da3dsoul** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/3e41e2a11f4034a68cc8fa746100b97304ee85b7

**Comment by da3dsoul** [comment]
Though, the timeout will still need to be increased. I can load 15000 files in under a minute now with tracing and debug enabled, but 95000 is flat out unreasonable for most users.

**Comment by da3dsoul** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/2e59cac8a77ea9087838f22d6e81ad1942a01cdd
Update to latest daily in both Server and Desktop, then give it a try. It'll likely still take a while, but less than 3 minutes, hopefully.

**Comment by kakure** [comment]
Apologies for the long waited reply.  I've updated both to the latest nightly, and it's working.  It loaded 93k files in a couple seconds.  Nice work!

**Comment by da3dsoul** [comment]
Sweet! Closed
