### ISSUE TITLE
AniDB AV Dump UTF-16/32 Issue

### ISSUE THREAD

**Issue by kakure** [ShokoAnime/ShokoDesktop#572]
## VERSION INFORMATION

Server Version: Latest Nightly Build

Desktop Version:  Latest Nightly Build

## LOG FILE

No log is necessary for this, see screenshot attached; displays the issue

## DESCRIPTION

When I try to dump files to AniDB, that are in a different language (such as Japanese), the ED2k dump results are all question marks (non-unicode compliant results).  This makes copy-paste results into AniDB useless.  I am able to normally copy / paste other unicode languages, so my Windows OS should not require anything installed to be compliant to see / interact with unicode characters; I can see, copy, paste Japanese from notepad++, browsers, etc. without issue.  

I've got the Japanese language pack installed for Windows 10.  I've also already got the .NET language pack for 4.7 installed.

Screenshot attached.

Before pressing dump button:
![before pressing dump option](https://user-images.githubusercontent.com/27033914/34178914-e0a2e27c-e4d6-11e7-8a57-294e5c0dbfcc.png)

After pressing dump button:
![after pressing dump option](https://user-images.githubusercontent.com/27033914/34178921-e607c89a-e4d6-11e7-877f-920986a69f5f.png)

## STEPS TO REPRODUCE

Use files that contain Japanese language, and try to use the AV Dump option.

**Comment by da3dsoul** [comment]
PM me the source for one of those files. I'll look at it

**Comment by kakure** [comment]
Not sure the source is available anymore.  Any file with Japanese characters in its name should work as a test.

**Comment by kakure** [comment]
Performed a manual dump per da3dsoul's suggestion; the output file does contain question marks.  Attached sample.
[sample.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1573255/sample.txt)

**Comment by ElementalCrisis** [comment]
Not an issue on our side, its a Windows issue.

Setting the region to Japan should fix it.

**Comment by kakure** [comment]
Tried to set Windows 10 to Japanese region, and verified that I could type into text editors in Japanese.  However, when it came to the Command Window Prompt, i got some crazy characters.  I tried to re-run the ED2k test, and got the same question mark results as before.

**Comment by da3dsoul** [comment]
I'm going to reopen this, but because we could do this differently to support it. From what I could tell, you can output to file instead of console, which works, and we can read the file.
