### ISSUE TITLE
Fresh downloaded episode images only visible after restart

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#573]
If you update TVDB data, and missing episode images are being downloaded,
they only get displayed after a program restart.

If you reload the series, only the last unwatched episode on "Series Info"- Tab gets updated.
The images on "Episodes"- Tab wont be shown.

Version:
3.8.2.0 Stable

Reproduce:  
1. Find Series with missing episide images
2. Hit update button next to TVDB Link
3. Wait for images download finished
4. Refresh Series and check "Episodes"- Tab

**Comment by da3dsoul** [comment]
I'm fully aware. Was there not an issue already? Oh well. It's an issue in Desktop that is too much of a pain for me to fix. If anyone else wants to try, then go for it.

**Comment by da3dsoul** [comment]
Fixed
