### ISSUE TITLE
Editing A Group AND Not Saving Blanks Group

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#576]
## VERSION INFORMATION

Server Version: 3.8.2.35
Desktop Version: 3.8.2

If you've compiled your own version, please use the last commit you compiled.

## DESCRIPTION

Editing a group but making no changes blanks the group and sort name.

## STEPS TO REPRODUCE

1. Select group to edit.
2. Cancel edit.

![2018-01-09_17-19-16](https://user-images.githubusercontent.com/9443295/34751420-5d296e66-f561-11e7-99f8-f666a3528e74.gif)

**Comment by da3dsoul** [comment]
Does restarting bring it back, or does it actually wipe the titles?

**Comment by ElementalCrisis** [comment]
Restarting brings it back, however running Recreate All Groups while its gone freezes the Collection tab and the series panel appears on filter listing.

**Comment by da3dsoul** [comment]
Unassigning myself, because I don't wanna.
