### ISSUE TITLE
Ordering anime alphabetically

### ISSUE THREAD

**Issue by idrostasi** [ShokoAnime/ShokoDesktop#577]
It could be great if it will be possible to sort series inside group or subgroup alphabetically and not only by year. Great to replicate this type of sorting in the plugin for mediaportal, obviously

**Comment by da3dsoul** [comment]
It's more likely to happen in MA3 than Desktop. I have no motivation to add things to Desktop since we have ClientV2 in progress

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
