### ISSUE TITLE
Make player watchers for launching from folder

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/ShokoDesktop#582]
There's some features that we can't easily support, like linked chapters, external audio, etc that require launching files with the absolute path.
We can add the option for player watchers for some players, so that we can track watched states from server, and the files can be launched manually from the folder or from Desktop with the absolute path.

It's not high priority, but it's something some people would like for ease of use or wierd setups.

Thoughts?

**Comment by ElementalCrisis** [comment]
If we're going to go this route then each "supported" player should be separated so they can be updated as needed. The only "supported" players are MPC, VLC and Zoom Player. 

Automark and MPC Web UI Port are the only settings that are needed. Advanced settings as well as our Internal MPV player will of course still be tired to Desktop.

**Comment by da3dsoul** [comment]
I don't know for sure if Zoom Player is, but I think it is

**Comment by ElementalCrisis** [comment]
Its its, @RickDB added support for it awhile back.

**Comment by da3dsoul** [comment]
No I mean I don't know if we could do it like this for it. It requires a WebUI or file watcher with a way to tell what file is being played

**Comment by ElementalCrisis** [comment]
Ah, for MPV I wonder if we could use this script which adds a WebUI to it to make it work.

https://github.com/open-dynaMIX/simple-mpv-webui

**Comment by RickDB** [comment]
In theory we can watch if Zoom Player is running however users would need to have the API for it enabled if it's outside of ShokoDesktop, right now if we play via ShokoDesktop it adds an argument that enables this API for that session for us (requiring no setup).
Control API has plenty of options we can grab info from:

http://forum.inmatrix.com/index.php?showtopic=7051

**Comment by da3dsoul** [comment]
Okay

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
