### ISSUE TITLE
Default posters and banners appear blank

### ISSUE THREAD

**Issue by MaximoCutro** [ShokoAnime/ShokoDesktop#583]
## VERSION INFORMATION

Server Version: 3.8.3

Desktop Version: 3.8.3

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE

## DESCRIPTION

On the images tab for any series, you can pick the default poster and banner and they stick, but appear blank on the tab. Fanart works correctly, when you pick one the heart becomes red and the picture is used as default.  

Whether the images show up as default in Desktop or not, they don't seem to be used as default in My Anime 3.

## STEPS TO REPRODUCE

![baccano](https://user-images.githubusercontent.com/9994894/37007863-382d1a8a-20be-11e8-94ee-cdbbf0379af3.jpg)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
