### ISSUE TITLE
Allow to deselect files during automatic deletion

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoDesktop#585]
(Since this is no Issue,
but a request for enhancement, I'll leave out the usual information on top.)

Using ShokoDesktop -> Utilities -> Multiple Files -> Delete by Preferences,
allow to deselect files that you want to keep although they would get deleted by your preferences.
Marking @da3dsoul

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

@Baine please revisit this when testing the multiple files utility in Web UI.
