### ISSUE TITLE
Renaming script and file moving overwriting files

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#59]
**Reported by Are.Finstad, Aug 10, 2013**

_What steps will reproduce the problem?_
have two different versions of a episode, like a 1080p vid and a 720p vid. the same version but a different file (both are V1 of the release)

for example these two files:
http://anidb.net/perl-bin/animedb.pl?show=file&fid=1223248
http://anidb.net/perl-bin/animedb.pl?show=file&fid=1278835

this also confuses the JMM server. and the files does show up in Multiple files but JMM points both links to the same file, the entry can't be removed either.
after everything one of the files cant be found on the pc at all, its gone it seems. like it overwrite 

_What is the expected output? What do you see instead?_
i expect that it wont overwrite the file.

_Please provide any additional information below._
all my logs are backed-up here http://sdrv.ms/15CGuuI

My File Renaming Script (runs on import): 

```
// Sample Output: One Piece - 558 - The Noah Closing in! The Fish-Man Island Facing Destruction! [Kousei].mp4
// Anime Name, use english name if it exists, otherwise use the Romaji name
IF I(eng) DO ADD '%eng '
IF I(ann);I(!eng) DO ADD '%ann '
// Episode Number, don't use episode number for movies
IF T(!Movie) DO ADD '- %enr'
IF F(!1) DO ADD ' v%ver'
DO ADD  - %epr
IF I(grp) DO ADD ' [%grp]'
IF I(cen) DO ADD ' [%cen]'

// Replacement rules (cleanup)
DO REPLACE '_' ' ' // replace spaces with underscores
DO REPLACE 'H264/AVC' 'H264'
DO REPLACE '0x0' ''
DO REPLACE '__' '_'
DO REPLACE '__' '_'

// Replace all illegal file name characters
DO REPLACE '<' '('
DO REPLACE '>' ')'
DO REPLACE ':' '-'
DO REPLACE '"' '`'
DO REPLACE '/' '_'
DO REPLACE '/' '_'
DO REPLACE '\' '_'
DO REPLACE '|' '_'
DO REPLACE '?' ''
DO REPLACE '*' '_'
```

is this an error on my renaming script of can it be fixed in a way with an update?

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

https://github.com/ShokoAnime/ShokoServer/issues/504
