### ISSUE TITLE
Missing episodes icon is not always shown

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#594]
## VERSION INFORMATION

Server Version:  3.9.3
Desktop Version: 3.9.3

## DESCRIPTION

The missing episodes icon is not always shown when the series has missing episodes.
I can reproduce this on at least 10 series. Some series which do have missing episodes will show the icon though

## STEPS TO REPRODUCE

I have attached screenshots to show the issue.
I have also tried the following
- Run "Update All Stats" from Shoko Server
- Wait until completion
- Restarted Shoko Server
- Restarted Shoko Desktop

I have also tried using the "Update AniDB Info" button on the series and made sure the "Download release groups" option is enabled

![image](https://user-images.githubusercontent.com/6645153/50553202-17112b00-0cf6-11e9-8870-2a1d59d20ad7.png)

![image](https://user-images.githubusercontent.com/6645153/50553204-209a9300-0cf6-11e9-92a8-684279e83e60.png)

![image](https://user-images.githubusercontent.com/6645153/50553206-285a3780-0cf6-11e9-93b8-c9cdac52b567.png)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
