### ISSUE TITLE
searching in tags not working anymore for group filters

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#595]
## VERSION INFORMATION

Server Version: 3.9.4.30902

Desktop Version: 3.9.4.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

n/a

## DESCRIPTION

The search function under Collection/Groups wont search in Tags anymore.

## STEPS TO REPRODUCE

1. Collection Tab
2. select "all"
3. Search for "love polygon". 

There should be serveral series with this tag, but for me, i get 0 results.

(probably more of a server issue tho, since results are generated there...)

**Comment by da3dsoul** [comment]
I feel like it was disabled for performance reasons, as it's not background processing

**Comment by da3dsoul** [comment]
You can still search in the Search Tab

**Comment by da3dsoul** [comment]
Then that's a bug

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
