### ISSUE TITLE
Broken Translation of ShokoDesktop

### ISSUE THREAD

**Issue by jim-kirisame** [ShokoAnime/ShokoDesktop#599]
## VERSION INFORMATION

Server Version: v3.9.4.8440
Desktop Version: V3.9.4.0

## DESCRIPTION

Hello, I'm using the Shoko Desktop. It seems that the language switch on the right corner doesn't work at all. 

So is it a bug or a unimplement feature? I want to add chinese translation.

**Comment by da3dsoul** [comment]
It's a bug

**Comment by ElementalCrisis** [comment]
You might need to switch the language and then restart Desktop.

**Comment by ElementalCrisis** [comment]
No update, closing issue.
