### ISSUE TITLE
Use filters properly for playlists

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#60]
**Reported by Are.Finstad, Aug 26, 2013**

user can get into blocked content if they are in a playlist.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

As playback will no longer be possible, playlist functionality is not supported in the upcoming Web UI v4.
