### ISSUE TITLE
Missing episodes and calendar section always empty

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#601]
## VERSION INFORMATION

Server Version:  3.9.5

Desktop Version:  3.9.5

## LOG FILE

Server: 
[2019-08-17.log](https://github.com/ShokoAnime/ShokoDesktop/files/3511638/2019-08-17.log)

Client:
[2019-08-17.txt](https://github.com/ShokoAnime/ShokoDesktop/files/3511639/2019-08-17.txt)

## DESCRIPTION

With 3.9.5 the calendar and missing episode section always comes up empty.

![grafik](https://user-images.githubusercontent.com/10379828/63206452-d9121d00-c0b4-11e9-821c-e1365cea1e20.png)

## STEPS TO REPRODUCE

1. Have watched episodes
2. Have missing episodes in collection which are available
3. Check dashboard

**Comment by da3dsoul** [comment]
https://media.tenor.com/images/d77b603d20044e09224a47a9234c5dbd/tenor.gif

**Comment by Mik1ll** [comment]
Was fixed in https://github.com/ShokoAnime/ShokoServer/pull/791. Can close.
