### ISSUE TITLE
Watched state not possible for movie consisting of multiple episodes

### ISSUE THREAD

**Issue by Yhoogi1** [ShokoAnime/ShokoDesktop#603]
## VERSION INFORMATION

Server Version:  3.9.4 
Desktop Version: 3.9.4
Due to compatibility issue with Mediaportal / MyAnime not the most recent version is installed.
Changelog is not adressing a fix for this, though.
I presume it is still existing - TBC

## DESCRIPTION

trying to switch a movie to watched state fails if it is copmposed of multiple episodes
Example: https://anidb.net/anime/13473:

Movie 1 consists of 2 episodes located in "OTHER" and combined in "EPISODES" as 1 movie with 2 entries
Viewing them in "OTHER" will individually change the watched state.
In "EPISODES" the watched state is retained as unwatched
Neither manual switching of "MARK AS WATCHED" nor "MARK ALL AS WATCHED" is working in episode view nor in group views
Status remains in unwatched state

This behaviour is shown in Desktop as well as from MyAnime3. 

## STEPS TO REPRODUCE
Just use a movie which consists of multiple episode (see example above)

**Comment by Yhoogi1** [comment]
Just seen that the movie consists of 4 episodes
As only 2 eps are published the movie is not complete => behaviour correct

Counter-example (YAMATO)
Shows corret behaviour if all eps comprising the movie exist. Then movie can be correctly switched between the unwatched/watched state

**Comment by da3dsoul** [comment]
Thanks for the info. I wouldn't be surprised if that has issues.
