### ISSUE TITLE
Unintentional file deletion

### ISSUE THREAD

**Issue by xmodx10** [ShokoAnime/ShokoDesktop#604]
## VERSION INFORMATION

Server Version: Daily (24/09/2020)

Desktop Version: 4.0.0.0

## LOG FILE

-Desktop logs dont really show much
-Docker console logs do not show anything

## DESCRIPTION

Applies to when selecting to delete a file from either episode list or the "ignored" file list. May affect more areas as well.

You un-tick the "local file system" provider with the intention of it only deleting the record from the database, however it deletes the file!

![image](https://user-images.githubusercontent.com/25097788/94159675-662dc500-feb6-11ea-859b-4e07bc0f5b18.png)

## STEPS TO REPRODUCE

See above

**Comment by da3dsoul** [comment]
Personally, I don't see why you'd want files existing that Shoko can handle outside of Shoko. This isn't a bug, actually. It's a poor design decision from when cloud was added. It was intended that you could delete it from local but not cloud or whatever. If the checkbox is unchecked in that case, the intended behavior is to do nothing.

**Comment by xmodx10** [comment]
ah I see, so if un-ticketed its actually meant to do nothing at all. I'm having a look through the code and ill see if I can fix it up.

**Comment by da3dsoul** [comment]
On the server side, if you wanted to do what you're saying, you'd need to delete it, and then decide if you want it added to the ignored files list, as it'll just reimport on next scan

**Comment by xmodx10** [comment]
Thanks, Understood. Though we still have a bug with this to some degree as it is deleting files even when the checkbox is not selected. 

Ill see if I can fix it up so it does nothing if the checkbox is not selected, OR we could just remove the checkboxes & provider list alltogether and make it a simple yes/no dialog ?

What do you think, really there is now only 1 provider from what I can tell.

**Comment by da3dsoul** [comment]
I'm fine with removing it
