### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by scj643** [ShokoAnime/ShokoDesktop#607]
## VERSION INFORMATION

Server Version: 4.0.1.0

Desktop Version: 4.0.0.0

## DESCRIPTION

I run Shoko Server behind nginx with a virtual domain. I need to connect with SSL on port 443

I will attempt to make a PR to implement this.

**Comment by da3dsoul** [comment]
I can say it's not a priority. Security is getting better, but we're still a level of insecure that https serves basically no benefit. You are better off making a tunnel.
