### ISSUE TITLE
Custom Anime Info Window

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoDesktop#608]
When we go in a Anime Info Window, there is lots of unused place in the top right corner or bottom right corner...
Is it possible to put the custom tags or other infos here?

I show you an example:
![jmm - serie info window](https://cloud.githubusercontent.com/assets/9465756/5054806/c175dc18-6c59-11e4-80df-fa04861241f8.jpg)

I can't see all infos i must scroll down...

**Comment by ElementalCrisis** [comment]
With Shoko Desktop being in maintenance mode, these changes will not be made.

However, Desktop 2's series view does address these and other UI related issues from Desktop 1.
