### ISSUE TITLE
Request: File Renaming tab should show entire path to file instead of just filename

### ISSUE THREAD

**Issue by HalfBakedHotdog** [ShokoAnime/ShokoDesktop#614]
## VERSION INFORMATION

**OS Info:** Windows 10 Pro Version 21H1 64bit
**Server Version:** Shoko Server Daily (2021-08-26)
**Desktop Version:** Shoko Desktop Daily (2021-08-26)
**Plugins:** ScriptRenamer v1.7.2 (latest)

## LOG FILE
N/A

## DESCRIPTION
Currently only the old name and new name are displayed on the renamer tab.
Now that it's possible to select destinations with the renamer script, it should also include the path\to\the\file.ext

(Image in case it's not clear what I'm referring to)
![image](https://user-images.githubusercontent.com/89708295/131230976-a1859b84-6f4a-4401-853c-af530d65cc4d.png)

**Comment by da3dsoul** [comment]
I was going to just say no but default, but fine, that's fair

**Comment by ElementalCrisis** [comment]
Already planned for the new Web UI. 

Maybe @da3dsoul will make the change in Desktop.
