### ISSUE TITLE
Clicking on Anime in SEARCH does nothing

### ISSUE THREAD

**Issue by SomeRandomDude870** [ShokoAnime/ShokoDesktop#616]
## VERSION INFORMATION

Server Version: 1.1.1

Desktop Version: 4.1.1.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE
l

## DESCRIPTION
Yeah, the Search in Collection does not work properly. So, I use the Search in the Header.
It seems to work correctly. It shows the Anime it is supposed to show, but when I want to watch them, I can´t.
When I double click onto the Entry nothing happens.
The only thing I can do is to PIN the Entry and then watch it.
But I would like to watch it directly.

....or is it intended to be like that? Then the behaviour is stupid...

## STEPS TO REPRODUCE

Header _> Search -> search for something -> click on something ->nothing happens.

**Comment by da3dsoul** [comment]
Hit the 📌 button. It's by design....a bad design.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
