### ISSUE TITLE
Error when trying to install on D:\ drive

### ISSUE THREAD

**Issue by lsahnicne** [ShokoAnime/ShokoDesktop#618]
I am trying to install Shoko Desktop version 4.1.2. My system drive has a D:\ letter assigned to it. I leave the default destination in the installer "D:\Program Files (x86)\Shoko\Shoko Desktop" unchanged. Setup fails to complete with the following error:
`Setup was unable to create the directory "C:\ProgramData"`. I presume it assumes to be installed on C:\ drive despite destination being located on another drive.

**Comment by ElementalCrisis** [comment]
No, Shoko Desktop will be installed to your D drive, but it seems to fail when trying to create the Shoko Desktop folder inside the ProgramData folder. 

I've never seen that error reported, what verson of Windows are you running?

**Comment by lsahnicne** [comment]
It appears to be looking for the **ProgramData** folder in the wrong place then. At the time of installation attempt, my PC did not even have any drive mounted as C:\. Is this path "C:\ProgramData" hard-coded into installation program rather than %PROGRAMDATA% environment variable? I run Windows 7 SP1 x64.

**Comment by Cazzar** [comment]
Looks to be https://github.com/ShokoAnime/ShokoDesktop/blob/5a235ac51b284ec5e695d5a4ad02465f86e5b64f/Installer/ShokoDesktop.iss#L55

**Comment by ElementalCrisis** [comment]
I updated the install script and uploaded new install builds. 

Give it a go @lsahnicne.

**Comment by lsahnicne** [comment]
Installed successfully this time.

**Comment by ElementalCrisis** [comment]
Awesome, closing ticket.
