### ISSUE TITLE
AniDB update options mismatch with server

### ISSUE THREAD

**Issue by lsahnicne** [ShokoAnime/ShokoDesktop#619]
## VERSION INFORMATION

Server Version: 4.1.2.0

Desktop Version: 4.1.2.0

## DESCRIPTION

After installing a desktop application and logging in to server, the settings related to updating AniDB do not match those set in the server Web UI beforehand. 
![ShokoDesktop_drwNjjB552](https://user-images.githubusercontent.com/43319094/177740931-407ec309-ca11-4f3e-9b32-ef2c52270b64.png)
![vtKH3fHlCy](https://user-images.githubusercontent.com/43319094/177741057-cbbf3c9f-49fd-49a8-b9fe-ee7df429eea1.png)

Also it appears the settings from desktop application were applied, despite visually remaining unchanged in the Web UI, as the number of "general commands" (called AniDB Queue in desktop application) and "unrecognized files" began rising up after launching the desktop application - a behavior i assume to be in line with the option "automatically update anime & episode information" set to "every 12 hours" - a value shown in the desktop application UI as opposed to "once a month" in a server Web UI.

## STEPS TO REPRODUCE

Change the default settings in server Web UI, then install Shoko Desktop, connect and log in to server.

**Comment by ElementalCrisis** [comment]
It's not a bug but a design flaw. 

Changes made in Desktop will show in Web UI after a hard refresh but not in Desktop unless you reload desktop.
