### ISSUE TITLE
Be able to delete matched Episodes only when deleting everything from a release group

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#62]
**Reported by Are.Finstad, Sep 1, 2013**

be able to delete matched Episodes only when deleting everything from a release group.
as in be able to delete only the episodes that you have more than one of in the Multiple Files menu, and not deleting everything from the release group. 

**Sep 20, 2013 valkyria086**

Wait, you can do that already. See issue 478, i've shown a pic.

**Sep 22, 2013  Are.Finstad**

No, you dont understand.
Im asking for a mass deletion option to delete everything from a grupe that have more then one file.
The group deletion right now deletes everything from the grupe no matter if you have more then one file or not.

For example you are missing a file from another grupe but you want to keep that one missing file from the grupe you are deleting

**Comment by ElementalCrisis** [comment]
Already possible thanks to the changes @da3dsoul made.
