### ISSUE TITLE
[Feature Request] Linux version please!

### ISSUE THREAD

**Issue by dethmourne** [ShokoAnime/ShokoDesktop#626]
I just found Shoko Server and am enjoying the collection management it provides, but I'd love to use Desktop to be able to have its functionality - do you have any plans on making a native Linux version?

**Comment by da3dsoul** [comment]
Shoko Desktop is never getting a native Linux version, for many reasons, but the most important one is to that it's old and bad in a lot of ways. We are expanding the webui in Shoko Server to cover most, if not all of Desktop's features. It will be inherently cross platform, as a webui

**Comment by da3dsoul** [comment]
In the meantime, people have gotten Desktop to work in wine. There's a faq about it in wine hq

**Comment by revam** [comment]
There is also a link to a (hidden) guide in our faq.

**Comment by bigretromike** [comment]
Also there is more and more function that Desktop did in WebUI, still long way but still.
