### ISSUE TITLE
Playback button not working when Player is set to Windows Default

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#628]
## VERSION INFORMATION

Server Version:  4.2.1

Desktop Version:  4.2.1

## LOG FILE

n/a

## DESCRIPTION

The playback button does not launch the system default player anymore, despite setting it to use windows default video player in playback settings.

According to settings page, its configured properly.

![grafik](https://user-images.githubusercontent.com/10379828/229349197-771914d3-725b-4ad6-9aec-c8f5662227b3.png)

## STEPS TO REPRODUCE

1. Set video player to Windows default
2. Try to playback an episode

**Comment by WorstGirl** [comment]
Server Version: 4.2.2 (Docker)
Desktop Version: 4.2.1

Seconding this issue. Using 'External MPV' it is able to launch the MPV correctly, but when set to use the 'Windows Default' option, nothing happens at all.

![2023_04_21_021944_ShokoDesktop_rVKnqJlAkR](https://user-images.githubusercontent.com/37132854/233570267-5a773845-b926-449d-9f23-6f1cfe85e723.jpg)

**Comment by ElementalCrisis** [comment]
Desktop is in maintenance mode, we recommend using a media player like Plex, Jellyfin or Kodi for video playback.
