### ISSUE TITLE
Episode count shows 0 in series details

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#629]
## VERSION INFORMATION

Server Version:  4.2.1

Desktop Version:  4.2.1

## LOG FILE

n/a

## DESCRIPTION

In Series details page, the number of episodes is sometimes shown as 0, altho there are episodes present.

![grafik](https://user-images.githubusercontent.com/10379828/229368503-18e2f9b5-887d-4907-a912-b48b0db9f5d3.png)
(here its 0 count)

![grafik](https://user-images.githubusercontent.com/10379828/229368570-fd38c30c-bb85-4d29-97b6-91ddac0f31d5.png)
(here it seems to be ok)

## STEPS TO REPRODUCE

1. check various series details pages
(note on this: Its not for all series the case. For some series, the number of episodes is shown, for some not. So its kinda hard to reproduce i guess)

**Comment by revam** [comment]
Fixed in [Shoko Server v4.2.2](https://github.com/ShokoAnime/ShokoServer/releases/tag/v4.2.2)
