### ISSUE TITLE
Comments tab always empty (no comments are displayed anymore)

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoDesktop#630]
## VERSION INFORMATION

Server Version:  4.2.1

Desktop Version:  4.2.1

## LOG FILE
no errors present

## DESCRIPTION
Comments are no longer loaded / displayed under the comments tab.

![grafik](https://user-images.githubusercontent.com/10379828/231080338-907c141c-5f42-4944-a62f-cedc494b4c33.png)

Trakt token still valid.

## STEPS TO REPRODUCE
1. select popular anime with comments
2. check comments tab

**Comment by ElementalCrisis** [comment]
IIRC, they were removed as they were pretty pointless.
