### ISSUE TITLE
Desktop wont launch at all

### ISSUE THREAD

**Issue by isvein** [ShokoAnime/ShokoDesktop#634]
## VERSION INFORMATION

Server Version:  4.2.2.0

Desktop Version: 4.2.1

Windows 10 latest version

## DESCRIPTION
Installed Shoko-desktop, wont boot at all. Does not show up in task manager, does not produce any logs in 
/ProgramData\ShokoDesktop
Tried to reinstall.
I see in Revo Uninstaller that version 4.2.1 reports as 4.2.0 too
Tried to download the installer from both website and github, same happens. 
Tried to download the 4.2.0 installer, same happen, wont boot ether.

**Comment by da3dsoul** [comment]
Try deleting the settings file in ProgramData\ShokoDesktop

**Comment by da3dsoul** [comment]
Ok, can you check Event Viewer -> Application Logs

**Comment by isvein** [comment]
> Ok, can you check Event Viewer -> Application Logs

there we go :)

Faulting application name: ShokoDesktop.exe, version: 4.2.1.0, time stamp: 0x63ed8286
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3996, time stamp: 0xb756c9ff
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x5f38
Faulting application start time: 0x01da853bdbe82c7b
Faulting application path: C:\Program Files (x86)\Shoko\Shoko Desktop\ShokoDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5b8df77c-28a2-4f8d-9362-ae8269286783
Faulting package full name: 
Faulting package-relative application ID:

**Comment by da3dsoul** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.3-windows-x64-installer
Try that. Googling that code didn't give much

**Comment by isvein** [comment]
forgot to close yesterday
