### ISSUE TITLE
Shoko Desktop lacks HTTPS support

### ISSUE THREAD

**Issue by TMUniversal** [ShokoAnime/ShokoDesktop#636]
## VERSION INFORMATION

Server Version: 4.2.2.0

Desktop Version: 4.2.1.0

## LOG FILE

Not applicable

## DESCRIPTION

I employ an HTTP reverse proxy for security and routing (traefik v3). Shoko Desktop has all protocols hard-coded to `http://` and cannot attempt an HTTPS connection.

## STEPS TO REPRODUCE

Attempt to connect to Shoko Server behind a reverse proxy such as Apache 2 or traefik with HTTPS enabled.

**Comment by da3dsoul** [comment]
Shoko Desktop lacks authentication. It's awful. We're killing it.
Soon™ we'll have a new stable release with the new webui we've been designing and building for like 6 years.
Desktop will exist for that stable release while we get feedback and make some improvements, and then Desktop will be officially dead on the stable release after that.
