### ISSUE TITLE
JMM Desktop: Laptop crashed when running dashboard on fullscreen

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#64]
**Reported by valkyria086, Sep 20, 2013**

_What steps will reproduce the problem?_
1. Windows 7, JMMD 3.1.32.0.
2. On dashboard, click the full screen button on the top right corner. 
3. After a few minutes (less than 5), windows will suddenly shutdown. Not the proper shutdown sequence, but the my-screen-suddenly-goes-black type of shutdown.

_What is the expected output? What do you see instead?_
JMMD supposed to run, but my laptop crashed instead.

_Please provide any additional information below._
I suspected a hardware acceleration being enabled type of problem. Because i've similar issue with firefox and some other applications. My laptop goes black on me when running them. But turn off the hardware accel., problem gone. Anyway, it's just my guess, if it helps.

**Comment by ElementalCrisis** [comment]
User specific issue.
