### ISSUE TITLE
JMM Desktop: Most of the time, dashboard is buggy

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#65]
**Reported by valkyria086, Sep 20, 2013**

Just like the title said, from time to time i can't click on anything on the dashboard, especially the scroll button. From the image you can see my settings, but i can't set anything.
Look at my horizontal scroll bar, and look at how many sections i have enabled and look at the numbers too. Isn't the bar seems a bit too long? That's because it's not loading the other sections. And i still can't scroll. 

![dashboard bug 1](https://cloud.githubusercontent.com/assets/6645153/3975983/4036142e-2816-11e4-9bcd-ff7bfa9d25a0.JPG)

Clicking on the series still brings me to the series' screen, but i can't scroll. And not only that, the first time i click on a series, it will bring me to a blank screen first. To view it properly, i have to go to another tab and then return to dashboard.

![dashboard bug 2](https://cloud.githubusercontent.com/assets/6645153/3975987/4dae3c1c-2816-11e4-9be3-df35ed26f5a1.JPG)
![dashboard bug 3](https://cloud.githubusercontent.com/assets/6645153/3975988/52116086-2816-11e4-988c-d3cef38c3ce2.JPG)

And i found this just now, once i select an anime, dashboard will only display that anime. If i'm selecting another anime, it will still show the first anime i select. Like in the image, while the title and description said [Boku Imouto wa "Osaka Okan"], the image is clearly of Bakemonogatari. That's because i was selecting Bakemonogatari. And furthermore, i can't scroll, and there's no episode shown there at all. But clicking on the "Play" button will play Bakemonogatari correctly.

These all happens most of the times, but not all the times. If i'm lucky, then i can use it. Man i love the dashboard but...

![dashboard bug 4](https://cloud.githubusercontent.com/assets/6645153/3975991/5eec3088-2816-11e4-93e4-ee3373292236.JPG)

**Are.Finstad**

Sound like something weird is going on here..... Hmmmmm.
I would try to reinstall the program or even try to change to another database.
MySQL or MS......dont use the standard one.

Dont really see any other option here.
It might not be the JMM fault either.

Never had any of the problems myself and i have been using the server for years now.

Also i would reconmend that you stop using the dashboard and rather start using the collection menu instead since it have been in dev longer and is more stable and more updated then the new metro interface, even tho we have had that for months now.

And if you have to use the dashboard, i wounldnt use the metro display since its alittle buggy still.
The normal dashboard should be enough for you and is more stable. Atleast for me.

**Sep 23, 2013 valkyria086**

Hmm... but i don't think it's a database problem though.
Anyway, i am using the collection menu since the beginning. Only from the recent update i saw that the metro dash looks quite nice, so i thought of trying it. And yeah the normal dashboard is stable for me too.
I found this one yesterday night by accident: when the metro dash is buggy, i just switch back to normal dashboard and then switch back to metro again. I can use my metro nicely after that. It's not a proper fix, but hey at least it won't take more than 2 seconds to fix it. But anyway, thanks man.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the bug reported in this issue will not be looked into.
