### ISSUE TITLE
JMM Desktop: remember size and position of windows

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#73]
**Reported by misakitchi@yahoo.fr, Jan 29, 2014**

JMM Desktop and Server: remember size and position of windows

its very annoying to resize the window of JMM Desktop everytime i launch it...

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
