### ISSUE TITLE
JMM Desktop: in "Continue Watching..." only show episodes option

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#74]
**Reported by misakitchi@yahoo.fr, Jan 29, 2014**

JMM Desktop: in "Continue Watching..." i only want to see episodes, and not specials for example.

Can you add an option to only show episodes?

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
