### ISSUE TITLE
Non-existent duplicate files with dot at the end of folder name

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#76]
**Reported by enlait, Jun 8, 2014**

JMM lists duplicate files for some series(see attached screenshot), when folder does not exist (it's not even a valid name!)
Strangely, only some files are affected even for those series

![2014-06-08_18-14-14 jmm desktop](https://cloud.githubusercontent.com/assets/6645153/3977165/60d055f6-2833-11e4-9ad6-53ccc453063e.png)

**Comment by ElementalCrisis** [comment]
Seems more OS related as this has never been reported again or replicated.
