### ISSUE TITLE
Rule Based Renaming and Moving of Files

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#8]
Rule Based Renaming and Moving of files.

Possibly two interfaces for it one as default and other called advanced.

Standard:
Gui sort of rule management and maybe not as dynamic as advanced, but still easy enough to use and has enough for the average user

Advanced:
Written rules
IF A(####) DO MOVE "E:\Anime [A-J]\$AnimeTitle"; or something like that?

would also love, to somehow do IF AnimeTitle starts with A-J move to 1 if K -O move to 2, else move to 3.

I'm aware this wouldn't be an exactly easy thing to implement.

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/504

**Comment by ElementalCrisis** [comment]
This is a server related feature, not desktop.

Referenced in main issue on server.
