### ISSUE TITLE
high contrast client or a darker theme (maybe a Hex Color picker?)

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#80]
IMO it would be great with a High Contrast version of the client or a way to change the contrast.

heck even a full hex color picker would be great in my eyes (it would make every client have a personal look to it (you can even tie it to the user logged in so it shows the themes that user likes))

ofc something like this should only be used on open areas and text, not pictures and logos.

this would reduce strain of the eyes in longer periods and would be better when using the program in a dark area (like in the middle of night like i am all the time)

**Comment by naarcissus** [comment]
Gods... I need this, sooo BAD!

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
