### ISSUE TITLE
[enhancement] automatically disable thetvdb/trakt/themoviedb for adult H releases. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#82]
[enhancement] automatically disable thetvdb/trakt/themoviedb for adult H releases. 

noticed on alot of adult releases they find entries that have parts of the name and even just a few letters correct to make a match for metadata agents, as none of those support adult releases they should automatically be disabled searching for those agent ties once it got certain tags from AniDB/MAL.

this will ofc help out with the load of the server as it should clean up the catching list and aswell keep your Trakt profile clean.

**Comment by ElementalCrisis** [comment]
Discussed with @RickDB, this is probably more of a server request. 

If a series has this tag - http://anidb.net/perl-bin/animedb.pl?show=tag&tagid=2615&reltb=animetb we disable community links. During import Server can check for this tag and if found the series ability to link community sites is disabled preventing attempted and accidental linking.

**Comment by AreFinstad** [comment]
having custom tags to take control of this aswell could help. remember Future Diary ( https://anidb.net/perl-bin/animedb.pl?show=anime&aid=8395 ) showed up on that 18+ tag when its not hentai but still adult. 
custom tags could be used as an overwrite for either forcing it into no community links or forcing it to use it. so both ways.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

This will be a setting in the new Web UI.
