### ISSUE TITLE
support custom pictures for thumbnails and cover pictures. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#83]
this is mostly for adult releases once themoviedb/thetvdb metadata agents gets more support (like better direct linking between each file)

this can be done by loading images with preset names like other media server does it (folder.jpg for cover and [filename]-thumb.jpg)

you can make rules aswell for if there is none it will automatically use that one, if not it will use whats on the metadata agents (or random between them is also good :D) 

something like this will also open up more support for other media servers.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

This is a server request and is linked to the main server issue for reference, if needed.
