### ISSUE TITLE
write out metadata to series/movie folder in standard formats.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#84]
i think it would be great to support a way to write out the metadata you have on the series, episodes and movies. like Plex or MediaBrowser does it. 

uploaded and example on how MediaBrowser does it with its AniDB Agent and it also uses AniList, IMDb,TheMovieDB,TheTVDB,TV.com and Zap2it to find its data and its cross references between them. 
https://mega.co.nz/#!cwg3AAbD!eq2QEi8Htn__IOxVXjFRVwmzX9A5IJ25IrTis7lXGWo

as you see it contains very few files but has the info needed right there.

by supporting that + adding thetvdb season script support to the renaming scripting and make season folders it will work across most media servers. 

ofc the only thing that can be a problem is how you should handle the metadata files once the files are moved, i guess you can have a list witch get checked each time you click a button and that will delete all metadata files that have missing video files (if you say move one episode to another location) this way it will also help cleaning up the meta files aswell if you rename the files. 

ofc there also must be a simple way to get new meta files aswell if they are not together with the video file.

**Comment by AreFinstad** [comment]
i really dont see much downsides to doing all Metadata on the server like this. Media Browser and many other media servers handles meta files this way flawlessly.
here is some Pros and Cons for having the Metadata with the files themselfs.

Pros:
Data can easily be found, and in an intuitive structure if you want to edit it.
HDD usage is spread over all your drives so people with small drives can still do this with no issues.
Easier to Copy/Paste/Share
User Watchstates can follow the files for many users. (dont need to sync with Trakt/AniDB for things to stay up-to-date if you have watched it offline)
cross-compatibility with other systems/servers
easier maintenance of media
Metadata is always backed up with the files incase of database loss.
Faster to rebuild libraries.
Saves bandwidth on both the user side aswell as Metadata providers if they are local.

Cons: 
Metadata is not stored in a central location. (cant edit it easily at all in JMM ATM)

--------------------
JMM:
Pros:
everything is pretty much flawless when it comes to downloading the right Metadata from AniDB (not yet there with thetvdb before admin/community controlled cross linking)

Cons:
everything has to be downloaded again if database is lost/remade.
does not work with other media servers unless making systems for it like the plex app
no real way to edit/copy and so on either.

**Comment by AreFinstad** [comment]
related: https://github.com/japanesemediamanager/jmmserver/issues/7

**Comment by ElementalCrisis** [comment]
Not in the current design spec for Shoko.
