### ISSUE TITLE
support thetvdb Seasons folder structure.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#86]
[enhancement] support thetvdb Seasons folder structure for folders inside each series.

we should be able to have the JMM system to place episode files (and Metadata files if you saw my other "issue") inside season named folders. these should follow thetvdb standard IMO as that is what others are using aswell. this should work with the season renaming rules aswell 

if series is not layed out this way then both Plex and MediaBrowser (others too BTW..... but thats what im using ATM) get confused between whats a series and whats a movie. 

see my other "issues" i made aswell about supporting standard metadata uses.

by using something like this then we dont need the plex app we have ATM, we can just add the folders to plex like any other media (tvshows and such) 

ofc something like this will also support alot more than just plex and that gives everyone a choice in what kind of streaming server they would like to use. (Kodi (XBMC), MediaBrowser, Plex, Serviio, Subsonic, PlayOn, Samsung AllShare, Windows Media Server? and more i guess......)

**Comment by anzerman** [comment]
:+1:

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/ShokoServer/issues/504

**Comment by ElementalCrisis** [comment]
TVDB is being removed as they are no longer providing a free API.
