### ISSUE TITLE
Feature request Monitor Anime

### ISSUE THREAD

**Issue by saitoh183** [ShokoAnime/ShokoDesktop#87]
As it stands right now, JMM is shaping up to be a very complete package for managing our anime collection. The only thing i see that is missing would be a Calendar for on-going anime that we are collecting and JMM monitoring torrent feeds for new and missing eps...basically sickbeard/nzbdrone functionallity. We can already manually search torrents sites for missing episode and you can also already link utorrent to jmm

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

The Web UI has a calendar on the dashboard that shows series you are currently watching that are also airing.
