### ISSUE TITLE
[enhancement] Better Thumbnail Management 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#88]
make JMM be able to detect if there is a thumbnail is saved on your server if not check for thumbnail at thetvdb site and download, if its not there add the episode (important that its per episode basis and not series) to a list that lists missing thumbs.

also, should have quicklinking to thetvdb episode page directly for easy access to upload.

also have notes to ask people to help out to upload missing pictures and inform users with the thumb rules that thetvdb uses (size and format). also inform easy ways they can do this and tell them to keep it spoiler free.

also should be a simple way to report/mark a thumbnail if they are worse quality than exists (say thumbs with overlays or subs included or something, best BD source thumbs should be used for the best pictures obv.)
marking can also be used if there is spoilers in the thumbnail.

marking is good for users to share info to eachother and to just mark them for needing work later.

**Comment by AreFinstad** [comment]
this should be worked into the Community Review Tab or Community Data Tab, one of the others.
as a start it should see if there is missing images/thumbs of the series you have on drive. 
we should also be able to see all the thumbs that already is on thetvdb service to checkout the quality and so on if it needs to be changed (wrong ration, random text in shot and so on)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Already linked to the main server issue for Image Management.
