### ISSUE TITLE
NZB support

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#9]
I can see you have torrent support (although is it only from the myanime plugin?) 
would it be possible to add NZB support. As well as adding both torrent and NZB config to the server or desktop apps?

If it helps I use the following software:
sabNZBd:
http://sabnzbd.org/
Sick-Beard:
http://sickbeard.com/
Sick-Beard (anime branch):
https://github.com/lad1337/Sick-Beard

**Comment by anzerman** [comment]
I still use nzbs, however I can see that this is a lower priority for the majority of people.

**Comment by ElementalCrisis** [comment]
We no longer support downloading.
