### ISSUE TITLE
[enhancement] detect if missing episode description or low quality one's

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#90]
[enhancement] detect if missing episode description or low quality one's.
JMM should detect if description is missing and blank or if it contains too few words (say if it contains less than 15-20 words or something) for a full description of the episode. 

this should also make a list like in the missing thumbs list i have talked about here: https://github.com/japanesemediamanager/jmmclient/issues/88

with these two in place it would be alot simpler for users to help out with for filling metadata for JMM to use.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Not something I see much use in adding anyway.
