### ISSUE TITLE
Dashboard unloads images if too many is loaded in. 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#96]
Dashboard unloads images if too many is loaded in. 
say you have "Recent Additions" and "Continue Watching..." tabs open and they load all images correctly. if i also open up the "Mini Calendar" the images from the "Continue Watching..." tab gets unloaded and is replaced by a white window.
this is only happening with the "Mini Calendar" and none of the other tabs (can actually have all other tabs open without having the issue).

this seems to only be happening with the "Continue Watching..." tab and not the "Recent Additions" tab at all, those thumbnails are still loaded. 

this issue is just happening when you reload the dashboard, you can reload the tabs with the calendar hidden and then unhide it after the reload is done and all will be shown. 

here is a show of how its shown.
![](http://puu.sh/cANvV/3f7414508d.png)

and my logs are hosted here: https://mega.co.nz/#F!JsJxUKQD!kaUdPc5vx_yUZ0nxidsrSQ

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the bug reported in this issue will not be looked into.
