### ISSUE TITLE
[enhancement] UI choices in most tabs.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#98]
we have the JMM Desktop Dashboard that supports the standard list view with scrolling to the side with info on either episodes or shows with cover art and thumbs.
but the dashboard also support the "metro view" (im guessing its coming from the Win8 Metro Menu) witch has a nice cover concentric display. 

what would be good IMO for the Desktop app is more choices in how the UI is and works one the Dashboard/Collection/Playlist/Pinned tabs. 
i know UI's like this is mostly for MediaPlayers, but i think alot more people use the desktop over a mediaplayer for JMM usage...... maybe that just me.

"some" ways UI is done and can prob be done in the desktop aswell:

![](http://puu.sh/cEm7R/b351eca592.png)
![](http://puu.sh/cEmav/4f05138463.png)
![](http://puu.sh/cEmdY/2f78e22349.png)
![](http://www.viewfinderdesign.co.uk/wp-content/uploads/2009/06/mediacentre_movies.jpg)

i for one would love to have something like the Metro display we have now on the dashboard but also on the collection/pinned tabs that is constrained by the rules of those tabs (like group filters, searches for names and tags and sorting)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
